# Generated by Codex on 2026-05-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model_hub", "0089_merge_20260422_1854"),
        ("model_hub", "0089_merge_20260423_0001"),
    ]

    operations = []
