# Generated by Django 5.1.8 on 2026-06-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_hub", "0101_backfill_composite_v1_config_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="row",
            name="source_span_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="row",
            name="source_trace_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
