# Generated by Django 5.1.8 on 2026-07-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_hub", "0102_row_source_span_id_row_source_trace_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="row",
            name="source_span_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="row",
            name="source_trace_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
