# Generated by Django 5.1.8 on 2026-05-29 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0104_merge_20260526_0921'),
        ('simulate', '0074_canonicalize_simulate_eval_config_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizedataset',
            name='run_test',
            field=models.ForeignKey(blank=True, help_text='Run test this optimization run is linked to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimization_runs', to='simulate.runtest'),
        ),
        migrations.AddField(
            model_name='optimizedataset',
            name='test_execution',
            field=models.ForeignKey(blank=True, help_text='Test execution this optimization run was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimization_runs', to='simulate.testexecution'),
        ),
    ]
