# Generated by Django 5.1.8 on 2026-06-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0105_optimizedataset_run_test_and_more'),
        ('model_hub', '0106_decouple_telemetry_fk_constraints'),
    ]

    operations = [
    ]
