# Generated by Django 5.1.8 on 2026-06-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0107_merge_20260604_0609'),
        ('model_hub', '0110_merge_20260609_1253'),
    ]

    operations = [
    ]
