# Generated by Django 5.1.8 on 2026-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0120_backfill_score_tracer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaltemplate',
            name='mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Variable→trace-field mapping chosen on the Tracing test tab.', null=True),
        ),
        migrations.AddField(
            model_name='evaltemplate',
            name='tracing_project_id',
            field=models.UUIDField(blank=True, help_text='Project selected on the Tracing test tab.', null=True),
        ),
        migrations.AddField(
            model_name='evaltemplateversion',
            name='mapping',
            field=models.JSONField(blank=True, help_text='Variable→trace-field mapping at this version. NULL on pre-snapshot versions.', null=True),
        ),
        migrations.AddField(
            model_name='evaltemplateversion',
            name='tracing_project_id',
            field=models.UUIDField(blank=True, help_text='Tracing project selected at this version. NULL on pre-snapshot versions.', null=True),
        ),
    ]
