# Generated by Django 5.1.8 on 2026-06-08 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracer", "0080_alter_tracescanconfig_sampling_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvalTaskProcessedEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_id", models.CharField(max_length=255)),
                (
                    "eval_task_logger",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_entities",
                        to="tracer.evaltasklogger",
                    ),
                ),
            ],
            options={
                "db_table": "tracer_eval_task_processed_entity",
                "unique_together": {("eval_task_logger", "entity_id")},
            },
        ),
    ]
