# Generated by Django 5.1.8 on 2026-06-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('tracer', '0080_alter_tracescanconfig_sampling_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='evallogger',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=16),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='evallogger',
                    index=models.Index(fields=['eval_task_id', 'status'], name='eval_logger_task_status_idx'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "eval_logger_task_status_idx" ON "tracer_eval_logger" ("eval_task_id", "status");',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "eval_logger_task_status_idx";',
                ),
            ],
        ),
    ]
