# Generated by Django 5.1.8 on 2026-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0082_decouple_trace_session_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observabilityprovider',
            name='provider',
            field=models.CharField(choices=[('vapi', 'Vapi'), ('eleven_labs', 'Eleven Labs'), ('retell', 'Retell'), ('livekit', 'LiveKit'), ('others', 'Others'), ('deepgram', 'Deepgram'), ('agora', 'Agora'), ('pipecat', 'Pipecat'), ('bland', 'Bland.ai'), ('twilio', 'Twilio')], max_length=255),
        ),
        migrations.AlterField(
            model_name='useralertmonitor',
            name='metric_type',
            field=models.CharField(choices=[('count_of_errors', 'Count of errors'), ('error_rates_for_function_calling', 'Error rates for function calling'), ('error_free_session_rates', 'Error free session rates'), ('service_provider_error_rates', 'Service provider error rates'), ('llm_api_failure_rates', 'LLM API failure rates'), ('span_response_time', 'Span response time'), ('llm_response_time', 'LLM response time'), ('token_usage', 'Token usage'), ('daily_tokens_spent', 'Daily tokens spent'), ('monthly_tokens_spent', 'Monthly tokens spent'), ('evaluation_metrics', 'Evaluation metrics'), ('sim_eval_score', 'Simulation eval score (avg)'), ('sim_failure_rate', 'Simulation failure rate')], max_length=100),
        ),
    ]
