# Generated by Django 5.1.8 on 2026-06-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0083_alter_observabilityprovider_provider_and_more'),
        ('tracer', '0083_merge_20260610_1220'),
    ]

    operations = [
    ]
