# Generated by Django 5.1.8 on 2026-08-18 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_sosloginproxy'),
        ('tracer', '0096_repair_scanner_cluster_error_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CekuraIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signing_secret', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cekura_integrations', to='accounts.organization')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cekura_integration', to='tracer.project')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cekura_integrations', to='accounts.workspace')),
            ],
            options={
                'db_table': 'tracer_cekura_integration',
                'indexes': [models.Index(fields=['project', 'enabled'], name='tracer_ceku_project_ad9802_idx')],
            },
        ),
    ]
