# Generated by Django 5.1.8 on 2026-09-17 10:29
# Initial Error Feed v2 schema; Omega has not shipped before this migration.

import django.db.models.deletion
import uuid
from django.db import migrations, models


def move_scan_configs_to_omega(apps, schema_editor):
    config = apps.get_model('tracer', 'TraceScanConfig')
    config._base_manager.using(schema_editor.connection.alias).update(
        scan_version='omega-v1'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_gcpmarketplaceprocessedevent_gcpmarketplaceaccount_and_more'),
        ('tracer', '0098_observabilityprovider_poll_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceInvestigationEvidenceReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_id', models.CharField(max_length=128)),
                ('ordinal', models.PositiveIntegerField()),
                ('span_id', models.CharField(max_length=64)),
                ('parent_span_id', models.CharField(blank=True, max_length=64, null=True)),
                ('excerpt', models.TextField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tracer_trace_investigation_evidence_receipt',
            },
        ),
        migrations.AddField(
            model_name='tracescanconfig',
            name='omega_last_claimed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tracescanconfig',
            name='omega_limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tracescanconfig',
            name='omega_memory',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tracescanconfig',
            name='scan_version',
            field=models.CharField(default='omega-v1', max_length=20),
        ),
        migrations.RunPython(move_scan_configs_to_omega, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TraceInvestigationFinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('finding_id', models.CharField(max_length=128)),
                ('ordinal', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=64)),
                ('statement', models.TextField()),
                ('recovery', models.CharField(max_length=64)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_findings', to='tracer.traceerrorgroup')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_finding',
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationAttribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('span_id', models.CharField(blank=True, max_length=64, null=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='tracer.traceinvestigationfinding')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_attribution',
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationFindingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.traceinvestigationevidencereceipt')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.traceinvestigationfinding')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_finding_evidence',
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField()),
                ('root_span_id', models.CharField(max_length=64)),
                ('root_end_time', models.DateTimeField()),
                ('generation', models.PositiveBigIntegerField(default=1)),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('not_before', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.project')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.workspace')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_job',
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.PositiveBigIntegerField()),
                ('worker_id', models.CharField(max_length=255)),
                ('engine_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='claimed', max_length=20)),
                ('lease_token_digest', models.CharField(max_length=64)),
                ('lease_expires_at', models.DateTimeField()),
                ('read_cutoff', models.DateTimeField()),
                ('memory_snapshot_id', models.CharField(max_length=128)),
                ('memory_digest', models.CharField(max_length=71)),
                ('memory', models.JSONField(default=list)),
                ('limits', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tracer.traceinvestigationjob')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_attempt',
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('result_digest', models.CharField(max_length=71)),
                ('contract_version', models.CharField(max_length=64)),
                ('evidence_digest', models.CharField(max_length=71)),
                ('execution_status', models.CharField(max_length=20)),
                ('outcome', models.CharField(max_length=20)),
                ('coverage_scope', models.CharField(max_length=255)),
                ('observed_span_count', models.PositiveIntegerField()),
                ('read_complete', models.BooleanField()),
                ('future_arrivals_known', models.BooleanField()),
                ('model_calls', models.PositiveIntegerField()),
                ('input_tokens', models.PositiveBigIntegerField()),
                ('output_tokens', models.PositiveBigIntegerField()),
                ('cost_usd', models.DecimalField(decimal_places=9, max_digits=20, null=True)),
                ('cost_status', models.CharField(max_length=64)),
                ('grouping_status', models.CharField(choices=[('pending', 'Pending'), ('not_required', 'Not Required'), ('stale', 'Stale'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='tracer.traceinvestigationattempt')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tracer.traceinvestigationjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.project')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.workspace')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_report',
            },
        ),
        migrations.AddField(
            model_name='traceinvestigationjob',
            name='current_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_jobs', to='tracer.traceinvestigationreport'),
        ),
        migrations.CreateModel(
            name='TraceInvestigationGatewayCall',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('model_used', models.CharField(max_length=255)),
                ('cost_usd', models.DecimalField(decimal_places=9, max_digits=20, null=True)),
                ('input_tokens', models.PositiveBigIntegerField(null=True)),
                ('output_tokens', models.PositiveBigIntegerField(null=True)),
                ('total_tokens', models.PositiveBigIntegerField(null=True)),
                ('cached_input_tokens', models.PositiveBigIntegerField(null=True)),
                ('reasoning_output_tokens', models.PositiveBigIntegerField(null=True)),
                ('cache_status', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('http_status', models.PositiveSmallIntegerField(null=True)),
                ('retry_of', models.PositiveIntegerField(null=True)),
                ('retry_delay_ms', models.PositiveIntegerField(null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_calls', to='tracer.traceinvestigationreport')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_gateway_call',
            },
        ),
        migrations.AddField(
            model_name='traceinvestigationfinding',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='tracer.traceinvestigationreport'),
        ),
        migrations.AddField(
            model_name='traceinvestigationevidencereceipt',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_receipts', to='tracer.traceinvestigationreport'),
        ),
        migrations.CreateModel(
            name='TraceInvestigationRequirementCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_id', models.CharField(max_length=128)),
                ('ordinal', models.PositiveIntegerField()),
                ('requirement', models.TextField()),
                ('status', models.CharField(max_length=64)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_checks', to='tracer.traceinvestigationreport')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_requirement_check',
            },
        ),
        migrations.AddField(
            model_name='traceinvestigationfinding',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='tracer.traceinvestigationrequirementcheck'),
        ),
        migrations.CreateModel(
            name='TraceInvestigationRequirementEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.traceinvestigationevidencereceipt')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.traceinvestigationrequirementcheck')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_requirement_evidence',
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationVerificationReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_id', models.CharField(max_length=128)),
                ('ordinal', models.PositiveIntegerField()),
                ('executed', models.BooleanField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_receipts', to='tracer.traceinvestigationreport')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_verification_receipt',
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('partition', models.PositiveIntegerField()),
                ('offset', models.PositiveBigIntegerField()),
                ('event_id', models.UUIDField()),
                ('payload_digest', models.CharField(max_length=71)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.project')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.workspace')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_delivery',
                'constraints': [models.UniqueConstraint(fields=('organization', 'event_id'), name='unique_trace_investigation_event')],
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationAttributionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.traceinvestigationattribution')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.traceinvestigationevidencereceipt')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_attribution_evidence',
                'constraints': [models.UniqueConstraint(fields=('attribution', 'evidence'), name='unique_inv_attribution_evidence')],
            },
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationattribution',
            constraint=models.UniqueConstraint(fields=('finding', 'role'), name='unique_inv_finding_role'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationfindingevidence',
            constraint=models.UniqueConstraint(fields=('finding', 'evidence'), name='unique_inv_finding_evidence'),
        ),
        migrations.AddIndex(
            model_name='traceinvestigationattempt',
            index=models.Index(fields=['status', 'lease_expires_at'], name='trace_inv_attempt_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='traceinvestigationattempt',
            index=models.Index(fields=['job', 'status'], name='trace_inv_attempt_job_idx'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationattempt',
            constraint=models.UniqueConstraint(fields=('job', 'generation'), name='unique_trace_investigation_attempt'),
        ),
        migrations.AddIndex(
            model_name='traceinvestigationreport',
            index=models.Index(fields=['project', 'grouping_status', 'created_at'], name='trace_inv_report_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationreport',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='unique_trace_investigation_report_key'),
        ),
        migrations.AddIndex(
            model_name='traceinvestigationjob',
            index=models.Index(fields=['state', 'not_before'], name='trace_inv_job_due_idx'),
        ),
        migrations.AddIndex(
            model_name='traceinvestigationjob',
            index=models.Index(fields=['project', 'state'], name='trace_inv_job_project_idx'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationjob',
            constraint=models.UniqueConstraint(fields=('project', 'trace_id'), name='unique_trace_investigation_job'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationgatewaycall',
            constraint=models.UniqueConstraint(fields=('report', 'ordinal'), name='unique_inv_gateway_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationevidencereceipt',
            constraint=models.UniqueConstraint(fields=('report', 'evidence_id'), name='unique_inv_evidence_id'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationrequirementcheck',
            constraint=models.UniqueConstraint(fields=('report', 'requirement_id'), name='unique_inv_requirement_id'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationfinding',
            constraint=models.UniqueConstraint(fields=('report', 'finding_id'), name='unique_inv_finding_id'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationrequirementevidence',
            constraint=models.UniqueConstraint(fields=('requirement', 'evidence'), name='unique_inv_requirement_evidence'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationverificationreceipt',
            constraint=models.UniqueConstraint(fields=('report', 'receipt_id'), name='unique_inv_verification_id'),
        ),
    ]
