# Generated by Django 5.1.8 on 2026-09-17 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


def refuse_lossy_omega_report_migration(apps, schema_editor):
    report = apps.get_model('tracer', 'TraceInvestigationReport')
    if report._base_manager.using(schema_editor.connection.alias).exists():
        raise RuntimeError(
            'Existing Omega JSON reports require a verified relational backfill '
            'before dropping result and occurrences; legacy TraceScanResult data is unaffected.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0099_trace_investigation_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceInvestigationAttribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('span_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'tracer_trace_investigation_attribution',
            },
        ),
        migrations.AddField(
            model_name='traceinvestigationjob',
            name='current_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_jobs', to='tracer.traceinvestigationreport'),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='contract_version',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='cost_status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='cost_usd',
            field=models.DecimalField(decimal_places=9, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='coverage_scope',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='evidence_digest',
            field=models.CharField(max_length=71, null=True),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='execution_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='future_arrivals_known',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='input_tokens',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='model_calls',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='observed_span_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='outcome',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='output_tokens',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='traceinvestigationreport',
            name='read_complete',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='TraceInvestigationEvidenceReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_id', models.CharField(max_length=128)),
                ('ordinal', models.PositiveIntegerField()),
                ('span_id', models.CharField(max_length=64)),
                ('parent_span_id', models.CharField(blank=True, max_length=64, null=True)),
                ('excerpt', models.TextField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_receipts', to='tracer.traceinvestigationreport')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_evidence_receipt',
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationAttributionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.traceinvestigationattribution')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.traceinvestigationevidencereceipt')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_attribution_evidence',
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationFinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('finding_id', models.CharField(max_length=128)),
                ('ordinal', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=64)),
                ('statement', models.TextField()),
                ('recovery', models.CharField(max_length=64)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_findings', to='tracer.traceerrorgroup')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='tracer.traceinvestigationreport')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_finding',
            },
        ),
        migrations.AddField(
            model_name='traceinvestigationattribution',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='tracer.traceinvestigationfinding'),
        ),
        migrations.CreateModel(
            name='TraceInvestigationFindingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.traceinvestigationevidencereceipt')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.traceinvestigationfinding')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_finding_evidence',
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationGatewayCall',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('model_used', models.CharField(max_length=255)),
                ('cost_usd', models.DecimalField(decimal_places=9, max_digits=20, null=True)),
                ('input_tokens', models.PositiveBigIntegerField(null=True)),
                ('output_tokens', models.PositiveBigIntegerField(null=True)),
                ('total_tokens', models.PositiveBigIntegerField(null=True)),
                ('cached_input_tokens', models.PositiveBigIntegerField(null=True)),
                ('reasoning_output_tokens', models.PositiveBigIntegerField(null=True)),
                ('cache_status', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('http_status', models.PositiveSmallIntegerField(null=True)),
                ('retry_of', models.PositiveIntegerField(null=True)),
                ('retry_delay_ms', models.PositiveIntegerField(null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_calls', to='tracer.traceinvestigationreport')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_gateway_call',
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationRequirementCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_id', models.CharField(max_length=128)),
                ('ordinal', models.PositiveIntegerField()),
                ('requirement', models.TextField()),
                ('status', models.CharField(max_length=64)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_checks', to='tracer.traceinvestigationreport')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_requirement_check',
            },
        ),
        migrations.AddField(
            model_name='traceinvestigationfinding',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='tracer.traceinvestigationrequirementcheck'),
        ),
        migrations.CreateModel(
            name='TraceInvestigationRequirementEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.traceinvestigationevidencereceipt')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.traceinvestigationrequirementcheck')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_requirement_evidence',
            },
        ),
        migrations.CreateModel(
            name='TraceInvestigationVerificationReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_id', models.CharField(max_length=128)),
                ('ordinal', models.PositiveIntegerField()),
                ('executed', models.BooleanField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_receipts', to='tracer.traceinvestigationreport')),
            ],
            options={
                'db_table': 'tracer_trace_investigation_verification_receipt',
            },
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationevidencereceipt',
            constraint=models.UniqueConstraint(fields=('report', 'evidence_id'), name='unique_inv_evidence_id'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationattributionevidence',
            constraint=models.UniqueConstraint(fields=('attribution', 'evidence'), name='unique_inv_attribution_evidence'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationattribution',
            constraint=models.UniqueConstraint(fields=('finding', 'role'), name='unique_inv_finding_role'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationfindingevidence',
            constraint=models.UniqueConstraint(fields=('finding', 'evidence'), name='unique_inv_finding_evidence'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationgatewaycall',
            constraint=models.UniqueConstraint(fields=('report', 'ordinal'), name='unique_inv_gateway_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationrequirementcheck',
            constraint=models.UniqueConstraint(fields=('report', 'requirement_id'), name='unique_inv_requirement_id'),
        ),
        migrations.AddIndex(
            model_name='traceinvestigationfinding',
            index=models.Index(fields=['cluster'], name='trace_inv_finding_cluster_idx'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationfinding',
            constraint=models.UniqueConstraint(fields=('report', 'finding_id'), name='unique_inv_finding_id'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationrequirementevidence',
            constraint=models.UniqueConstraint(fields=('requirement', 'evidence'), name='unique_inv_requirement_evidence'),
        ),
        migrations.AddConstraint(
            model_name='traceinvestigationverificationreceipt',
            constraint=models.UniqueConstraint(fields=('report', 'receipt_id'), name='unique_inv_verification_id'),
        ),
        migrations.RunPython(refuse_lossy_omega_report_migration, migrations.RunPython.noop),
        migrations.RemoveField(model_name='traceinvestigationreport', name='active_projection_updated'),
        migrations.RemoveField(model_name='traceinvestigationreport', name='occurrences'),
        migrations.RemoveField(model_name='traceinvestigationreport', name='result'),
        migrations.AlterField(model_name='traceinvestigationreport', name='contract_version', field=models.CharField(max_length=64)),
        migrations.AlterField(model_name='traceinvestigationreport', name='evidence_digest', field=models.CharField(max_length=71)),
        migrations.AlterField(model_name='traceinvestigationreport', name='execution_status', field=models.CharField(max_length=20)),
        migrations.AlterField(model_name='traceinvestigationreport', name='outcome', field=models.CharField(max_length=20)),
        migrations.AlterField(model_name='traceinvestigationreport', name='coverage_scope', field=models.CharField(max_length=255)),
        migrations.AlterField(model_name='traceinvestigationreport', name='observed_span_count', field=models.PositiveIntegerField()),
        migrations.AlterField(model_name='traceinvestigationreport', name='read_complete', field=models.BooleanField()),
        migrations.AlterField(model_name='traceinvestigationreport', name='future_arrivals_known', field=models.BooleanField()),
        migrations.AlterField(model_name='traceinvestigationreport', name='model_calls', field=models.PositiveIntegerField()),
        migrations.AlterField(model_name='traceinvestigationreport', name='input_tokens', field=models.PositiveBigIntegerField()),
        migrations.AlterField(model_name='traceinvestigationreport', name='output_tokens', field=models.PositiveBigIntegerField()),
        migrations.AlterField(model_name='traceinvestigationreport', name='cost_status', field=models.CharField(max_length=64)),
    ]
