"""Additive and reversible: reversing removes revision and personal tab orders only.

Saved view records, ownership, visibility, configuration, and positions are preserved.
"""

# Generated by Django 5.1.8 on 2026-10-03 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_gcpmarketplaceprocessedevent_gcpmarketplaceaccount_and_more'),
        ('tracer', '0110_expand_investigation_requirement_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedview',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SavedViewTabOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tab_type', models.CharField(blank=True, choices=[('traces', 'Traces'), ('spans', 'Spans'), ('voice', 'Voice'), ('imagine', 'Imagine'), ('users', 'Users'), ('user_detail', 'User Detail'), ('sessions', 'Sessions')], max_length=20, null=True)),
                ('order', models.JSONField(blank=True, default=list)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_view_tab_orders', to='tracer.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_view_tab_orders', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_view_tab_orders', to='accounts.workspace')),
            ],
            options={
                'db_table': 'tracer_saved_view_tab_order',
                'indexes': [models.Index(fields=['user', 'workspace', 'project'], name='tracer_save_user_id_d05e60_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False), ('project__isnull', False)), fields=('user', 'workspace', 'project'), name='unique_saved_view_tab_order_per_user_project'), models.UniqueConstraint(condition=models.Q(('deleted', False), ('project__isnull', True)), fields=('user', 'workspace', 'tab_type'), name='unique_saved_view_tab_order_per_user_workspace_tab')],
            },
        ),
    ]
