# Generated by Django 5.1.8 on 2026-10-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracer", "0111_grouping_budget_wait"),
    ]

    operations = [
        migrations.AddField(
            model_name="traceerrorgroup",
            name="redirect_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redirected_from",
                to="tracer.traceerrorgroup",
            ),
        ),
    ]
