#!/bin/sh
set -eu

CONFIG_PATH="${CONFIG_PATH:-/usr/share/nginx/html/config.js}"

# Escape backslashes and quotes so values cannot break out of JS strings.
escape_js_string() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

CONFIG_NAMES="
VITE_HOST_API
VITE_HELP_LINK
VITE_INTERACTIVE_REQUEST_TIMEOUT_MS
VITE_ANALYTICS_REQUEST_TIMEOUT_MS
VITE_AGGREGATION_REQUEST_TIMEOUT_MS
VITE_FILTER_VALUE_REQUEST_TIMEOUT_MS
VITE_AGGREGATION_POLL_INITIAL_DELAY_MS
VITE_AGGREGATION_POLL_MAX_DELAY_MS
VITE_AGGREGATION_POLL_BACKOFF_FACTOR
VITE_AGGREGATION_POLL_MAX_ATTEMPTS
VITE_AGGREGATION_POLL_MAX_CONSECUTIVE_FAILURES
VITE_CURSOR_MAX_EMPTY_CONTINUATIONS
VITE_CHUNK_IMPORT_TIMEOUT_MS
VITE_CHUNK_IMPORT_MAX_RETRIES
VITE_CHUNK_IMPORT_RETRY_BASE_DELAY_MS
VITE_INTERACTIVE_MAX_PAGE_SIZE
VITE_PROPERTY_CATALOG_PAGE_SIZE
VITE_INTERACTIVE_TABLE_PAGE_SIZE
VITE_PROPERTY_CATALOG_SEARCH_PAGE_SIZE
VITE_PROPERTY_CATALOG_COMPACT_PAGE_SIZE
VITE_PROPERTY_CATALOG_LEGACY_PAGE_SIZE
VITE_PROPERTY_CATALOG_SEARCH_DEBOUNCE_MS
VITE_ATTRIBUTE_INVENTORY_SEARCH_DEBOUNCE_MS
VITE_FILTER_VALUE_SEARCH_DEBOUNCE_MS
VITE_FILTER_AUTO_APPLY_DEBOUNCE_MS
VITE_PROPERTY_CATALOG_STALE_TIME_MS
VITE_PROPERTY_CATALOG_CACHE_TIME_MS
VITE_PROPERTY_CATALOG_LEGACY_STALE_TIME_MS
VITE_PROPERTY_CATALOG_LEGACY_CACHE_TIME_MS
VITE_FILTER_VALUE_PAGE_SIZE
VITE_FILTER_VALUE_MIN_VISIBLE_RESULTS
VITE_FILTER_VALUE_STALE_TIME_MS
VITE_FILTER_VALUE_CACHE_TIME_MS
VITE_AUTOMATION_RULE_LIST_PAGE_SIZE
VITE_OBSERVE_PROJECT_PAGE_SIZE
VITE_EVAL_METRIC_MAX_WINDOW_DAYS
VITE_SIMULATION_PREVIEW_PAGE_SIZE
VITE_SIMULATION_PREVIEW_MAX_PAGE_SIZE
VITE_GROUND_TRUTH_DATASET_PAGE_SIZE
VITE_DATASET_ROW_ADJACENCY_MAX_ROWS
"

write_config_entry() {
  config_name="$1"
  config_value=$(printenv "$config_name" 2>/dev/null || :)
  config_value=$(escape_js_string "$config_value")
  printf '  %s: "%s",\n' "$config_name" "$config_value"
}

{
  printf '%s\n' 'window.__FUTURE_AGI_CONFIG__ = {'
  for config_name in $CONFIG_NAMES; do
    write_config_entry "$config_name"
  done
  printf '%s\n' '};'
} > "$CONFIG_PATH"

echo "[entrypoint] wrote ${CONFIG_PATH}"
exec "$@"
