/**
 * Starter widget templates for the widget editor.
 *
 * Each template provides a name, description, icon, and pre-filled
 * query_config / chart_config objects.  Selecting a template copies
 * these into the editor form so the user can customise and save.
 */

const WIDGET_TEMPLATES = [
  {
    id: "total-traces",
    name: "Total Traces",
    description: "Count of traces over time",
    icon: "mdi:chart-line",
    queryConfig: {
      metrics: [
        {
          id: "trace_count",
          name: "trace_count",
          displayName: "Trace Count",
          type: "system_metric",
          source: "traces",
          aggregation: "count",
        },
      ],
      filters: [],
      breakdowns: [],
      timeRange: { preset: "7D" },
      granularity: "day",
    },
    chartConfig: {
      chartType: "area",
      axisConfig: {
        leftY: {
          visible: true,
          label: "Traces",
          unit: "#",
          prefixSuffix: "prefix",
          abbreviation: true,
          decimals: 0,
          min: "",
          max: "",
          outOfBounds: "visible",
          scale: "linear",
        },
        rightY: {
          visible: false,
          label: "",
          unit: "",
          prefixSuffix: "prefix",
          abbreviation: true,
          decimals: 2,
          min: "",
          max: "",
          outOfBounds: "hidden",
          scale: "linear",
        },
        xAxis: { visible: true, label: "" },
        seriesAxis: {},
      },
    },
  },
  {
    id: "p95-latency",
    name: "P95 Latency",
    description: "95th percentile response latency over time",
    icon: "mdi:timer-outline",
    queryConfig: {
      metrics: [
        {
          id: "p95_duration",
          name: "p95_duration",
          displayName: "P95 Duration",
          type: "system_metric",
          source: "traces",
          aggregation: "p95",
        },
      ],
      filters: [],
      breakdowns: [],
      timeRange: { preset: "7D" },
      granularity: "day",
    },
    chartConfig: {
      chartType: "line",
      axisConfig: {
        leftY: {
          visible: true,
          label: "Latency",
          unit: "ms",
          prefixSuffix: "suffix",
          abbreviation: true,
          decimals: 0,
          min: "",
          max: "",
          outOfBounds: "visible",
          scale: "linear",
        },
        rightY: {
          visible: false,
          label: "",
          unit: "",
          prefixSuffix: "prefix",
          abbreviation: true,
          decimals: 2,
          min: "",
          max: "",
          outOfBounds: "hidden",
          scale: "linear",
        },
        xAxis: { visible: true, label: "" },
        seriesAxis: {},
      },
    },
  },
  {
    id: "error-rate",
    name: "Error Rate",
    description: "Percentage of traces with errors",
    icon: "mdi:alert-circle-outline",
    queryConfig: {
      metrics: [
        {
          id: "error_rate",
          name: "error_rate",
          displayName: "Error Rate",
          type: "system_metric",
          source: "traces",
          aggregation: "true_rate",
        },
      ],
      filters: [],
      breakdowns: [],
      timeRange: { preset: "7D" },
      granularity: "day",
    },
    chartConfig: {
      chartType: "line",
      axisConfig: {
        leftY: {
          visible: true,
          label: "Error Rate",
          unit: "%",
          prefixSuffix: "suffix",
          abbreviation: false,
          decimals: 1,
          min: 0,
          max: 100,
          outOfBounds: "hidden",
          scale: "linear",
        },
        rightY: {
          visible: false,
          label: "",
          unit: "",
          prefixSuffix: "prefix",
          abbreviation: true,
          decimals: 2,
          min: "",
          max: "",
          outOfBounds: "hidden",
          scale: "linear",
        },
        xAxis: { visible: true, label: "" },
        seriesAxis: {},
      },
    },
  },
  {
    id: "cost-by-model",
    name: "Cost by Model",
    description: "Token cost breakdown by model",
    icon: "mdi:credit-card-outline",
    queryConfig: {
      metrics: [
        {
          id: "total_cost",
          name: "total_cost",
          displayName: "Total Cost",
          type: "system_metric",
          source: "traces",
          aggregation: "sum",
        },
      ],
      filters: [],
      breakdowns: [
        {
          name: "model",
          displayName: "Model",
          type: "custom_attribute",
          source: "traces",
          attributeType: "string",
        },
      ],
      timeRange: { preset: "7D" },
      granularity: "day",
    },
    chartConfig: {
      chartType: "pie",
      axisConfig: {
        leftY: {
          visible: true,
          label: "Cost",
          unit: "$",
          prefixSuffix: "prefix",
          abbreviation: true,
          decimals: 2,
          min: "",
          max: "",
          outOfBounds: "visible",
          scale: "linear",
        },
        rightY: {
          visible: false,
          label: "",
          unit: "",
          prefixSuffix: "prefix",
          abbreviation: true,
          decimals: 2,
          min: "",
          max: "",
          outOfBounds: "hidden",
          scale: "linear",
        },
        xAxis: { visible: true, label: "" },
        seriesAxis: {},
      },
    },
  },
  {
    id: "traces-by-status",
    name: "Traces by Status",
    description: "Stacked count of traces grouped by status",
    icon: "mdi:chart-bar",
    queryConfig: {
      metrics: [
        {
          id: "trace_count",
          name: "trace_count",
          displayName: "Trace Count",
          type: "system_metric",
          source: "traces",
          aggregation: "count",
        },
      ],
      filters: [],
      breakdowns: [
        {
          name: "status",
          displayName: "Status",
          type: "custom_attribute",
          source: "traces",
          attributeType: "string",
        },
      ],
      timeRange: { preset: "7D" },
      granularity: "day",
    },
    chartConfig: {
      chartType: "stacked_column",
      axisConfig: {
        leftY: {
          visible: true,
          label: "Count",
          unit: "#",
          prefixSuffix: "prefix",
          abbreviation: true,
          decimals: 0,
          min: "",
          max: "",
          outOfBounds: "visible",
          scale: "linear",
        },
        rightY: {
          visible: false,
          label: "",
          unit: "",
          prefixSuffix: "prefix",
          abbreviation: true,
          decimals: 2,
          min: "",
          max: "",
          outOfBounds: "hidden",
          scale: "linear",
        },
        xAxis: { visible: true, label: "" },
        seriesAxis: {},
      },
    },
  },
];

export default WIDGET_TEMPLATES;
