export const WIDGET_TEMPLATES = [
  {
    id: "total_traces",
    name: "Total Traces",
    description: "Count of all traces over the last 7 days",
    icon: "mdi:chart-timeline-variant",
    chartName: "Total Traces",
    chartDescription: "Count of all traces over the last 7 days",
    timePreset: "7D",
    granularity: "day",
    chartType: "metric",
    metrics: [
      {
        id: "call_count",
        name: "Call Count",
        type: "system",
        source: "traces",
        dataType: "number",
        aggregation: "count",
      },
    ],
    filters: [],
    breakdowns: [],
  },
  {
    id: "eval_pass_rate",
    name: "Eval Pass Rate Over Time",
    description: "Average eval pass rate per day over the last 30 days",
    icon: "mdi:check-circle-outline",
    chartName: "Eval Pass Rate Over Time",
    chartDescription: "Average eval pass rate per day over the last 30 days",
    timePreset: "30D",
    granularity: "day",
    chartType: "line",
    metrics: [
      {
        id: "eval_pass_rate",
        name: "Eval Pass Rate",
        type: "system",
        source: "traces",
        dataType: "number",
        aggregation: "avg",
      },
    ],
    filters: [],
    breakdowns: [],
  },
  {
    id: "p95_latency",
    name: "p95 Latency",
    description: "95th-percentile request duration over the last 7 days",
    icon: "mdi:speedometer",
    chartName: "p95 Latency",
    chartDescription: "95th-percentile request duration over the last 7 days",
    timePreset: "7D",
    granularity: "day",
    chartType: "line",
    metrics: [
      {
        id: "duration",
        name: "Duration",
        type: "system",
        source: "traces",
        dataType: "number",
        aggregation: "p95",
      },
    ],
    filters: [],
    breakdowns: [],
  },
  {
    id: "top_error_clusters",
    name: "Top Error Clusters",
    description: "Error count by type over the last 7 days",
    icon: "mdi:alert-circle-outline",
    chartName: "Top Error Clusters",
    chartDescription: "Error count broken down by error type, last 7 days",
    timePreset: "7D",
    granularity: "day",
    chartType: "bar",
    metrics: [
      {
        id: "error_count",
        name: "Error Count",
        type: "system",
        source: "traces",
        dataType: "number",
        aggregation: "count",
      },
    ],
    filters: [],
    breakdowns: [
      {
        id: "error_type",
        name: "Error Type",
        type: "system",
        source: "traces",
      },
    ],
  },
  {
    id: "cost_by_model",
    name: "Cost by Model",
    description: "Total cost split by model over the last 30 days",
    icon: "mdi:currency-usd",
    chartName: "Cost by Model",
    chartDescription: "Total cost split by model, last 30 days",
    timePreset: "30D",
    granularity: "day",
    chartType: "pie",
    metrics: [
      {
        id: "cost",
        name: "Cost",
        type: "system",
        source: "traces",
        dataType: "number",
        aggregation: "sum",
      },
    ],
    filters: [],
    breakdowns: [
      {
        id: "model",
        name: "Model",
        type: "system",
        source: "traces",
      },
    ],
  },
];