# Code generated by scripts/generate-agentcc-gateway-contracts.py; DO NOT EDIT.
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class GatewayAdminContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)


class ProviderConfig(GatewayAdminContractModel):
    api_key: str | None = None
    base_url: str | None = None
    api_format: str | None = None
    models: list[str] | None = None
    timeout: int | None = None
    weight: float | None = None
    enabled: bool | None = None
    max_concurrent: int | None = None
    conn_pool_size: int | None = None
    aws_access_key_id: str | None = None
    aws_secret_access_key: str | None = None
    aws_region: str | None = None
    aws_session_token: str | None = None


class GuardrailCheck(GatewayAdminContractModel):
    enabled: bool | None = None
    action: str | None = None
    confidence_threshold: float | None = None
    config: dict[str, Any] | None = None


class GuardrailConfig(GatewayAdminContractModel):
    pipeline_mode: str | None = None
    fail_open: bool | None = None
    timeout_ms: int | None = None
    checks: dict[str, GuardrailCheck] | None = None


class ConditionalRoute(GatewayAdminContractModel):
    field: str | None = None
    operator: str | None = None
    value: Any | None = None
    target: str | None = None


class ComplexityTier(GatewayAdminContractModel):
    max_score: int | None = None
    model: str | None = None
    provider: str | None = None


class ComplexityRoutingConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    default_tier: str | None = None
    tiers: dict[str, ComplexityTier] | None = None
    weights: dict[str, float] | None = None


class FastestResponseConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    max_concurrent: int | None = None
    cancel_delay: str | None = None
    excluded_providers: list[str] | None = None


class ScheduledConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    max_pending_jobs: int | None = None
    result_ttl: str | None = None
    max_schedule_ahead: str | None = None
    retry_attempts: int | None = None
    worker_count: int | None = None


class SignalWeights(GatewayAdminContractModel):
    latency: float | None = None
    error_rate: float | None = None
    cost: float | None = None


class AdaptiveRoutingConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    learning_requests: int | None = None
    update_interval: str | None = None
    smoothing_factor: float | None = None
    min_weight: float | None = None
    signal_weights: SignalWeights | None = None


class ProviderLockConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    allowed_providers: list[str] | None = None
    deny_providers: list[str] | None = None


class AccessGroup(GatewayAdminContractModel):
    models: list[str] | None = None
    description: str | None = None
    aliases: dict[str, str] | None = None


class FailoverConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    max_attempts: int | None = None
    on_status_codes: list[int] | None = None
    on_timeout: bool | None = None
    per_attempt_timeout: str | None = None


class CircuitBreakerConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    failure_threshold: int | None = None
    success_threshold: int | None = None
    cooldown: str | None = None
    on_status_codes: list[int] | None = None


class RetryConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    max_retries: int | None = None
    initial_delay: str | None = None
    max_delay: str | None = None
    multiplier: float | None = None
    on_status_codes: list[int] | None = None
    on_timeout: bool | None = None


class MirrorRule(GatewayAdminContractModel):
    source_model: str | None = None
    target_provider: str | None = None
    target_model: str | None = None
    sample_rate: float | None = None


class MirrorConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    rules: list[MirrorRule] | None = None


class RoutingConfig(GatewayAdminContractModel):
    strategy: str | None = None
    fallback_enabled: bool | None = None
    fallback_on_status_codes: list[int] | None = None
    model_fallbacks: dict[str, list[str]] | None = None
    conditional_routes: list[ConditionalRoute] | None = None
    default_model: str | None = None
    complexity: ComplexityRoutingConfig | None = None
    fastest: FastestResponseConfig | None = None
    scheduled: ScheduledConfig | None = None
    adaptive: AdaptiveRoutingConfig | None = None
    provider_lock: ProviderLockConfig | None = None
    access_groups: dict[str, AccessGroup] | None = None
    failover: FailoverConfig | None = None
    circuit_breaker: CircuitBreakerConfig | None = None
    retry: RetryConfig | None = None
    mirror: MirrorConfig | None = None
    model_timeouts: dict[str, str] | None = None


class DiskCacheConfig(GatewayAdminContractModel):
    directory: str | None = None
    max_size_bytes: int | None = None
    compress: bool | None = None
    cleanup_interval: str | None = None


class RedisCacheConfig(GatewayAdminContractModel):
    address: str | None = None
    addresses: list[str] | None = None
    password: str | None = None
    db: int | None = None
    mode: str | None = None
    pool_size: int | None = None
    tls: bool | None = None
    key_prefix: str | None = None
    compress: bool | None = None


class S3CacheConfig(GatewayAdminContractModel):
    bucket: str | None = None
    prefix: str | None = None
    region: str | None = None
    access_key_id: str | None = None
    secret_access_key: str | None = None
    compress: bool | None = None


class AzureBlobCacheConfig(GatewayAdminContractModel):
    container: str | None = None
    prefix: str | None = None
    connection_string: str | None = None
    sas_token: str | None = None
    compress: bool | None = None


class GCSCacheConfig(GatewayAdminContractModel):
    bucket: str | None = None
    prefix: str | None = None
    project: str | None = None
    credentials_file: str | None = None
    compress: bool | None = None


class QdrantConfig(GatewayAdminContractModel):
    url: str | None = None
    collection: str | None = None
    api_key: str | None = None


class WeaviateConfig(GatewayAdminContractModel):
    url: str | None = None
    class_: str | None = Field(None, alias="class")
    api_key: str | None = None


class PineconeConfig(GatewayAdminContractModel):
    url: str | None = None
    api_key: str | None = None


class SemanticCacheConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    backend: str | None = None
    threshold: float | None = None
    dimensions: int | None = None
    max_entries: int | None = None
    qdrant: QdrantConfig | None = None
    weaviate: WeaviateConfig | None = None
    pinecone: PineconeConfig | None = None


class EdgeCacheConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    default_ttl: int | None = None
    max_size: int | None = None
    cacheable_models: list[str] | None = None
    require_opt_in: bool | None = None


class CacheConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    backend: str | None = None
    default_ttl: int | None = None
    max_entries: int | None = None
    disk: DiskCacheConfig | None = None
    redis: RedisCacheConfig | None = None
    s3: S3CacheConfig | None = None
    azure_blob: AzureBlobCacheConfig | None = None
    gcs: GCSCacheConfig | None = None
    semantic: SemanticCacheConfig | None = None
    edge: EdgeCacheConfig | None = None


class RateLimitConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    global_rpm: int | None = None
    global_tpm: int | None = None
    per_key_rpm: int | None = None
    per_key_tpm: int | None = None
    per_model_rpm: int | None = None
    per_user_rpm: int | None = None


class BudgetLevelConfig(GatewayAdminContractModel):
    limit: float | None = None
    period: str | None = None
    hard: bool | None = None
    action: str | None = None
    action_mode: str | None = None
    on_exceed: str | None = None
    per_model: dict[str, float] | None = None


class BudgetsConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    default_period: str | None = None
    warn_threshold: float | None = None
    org_limit: float | None = None
    org_period: str | None = None
    hard_limit: bool | None = None
    action: str | None = None
    action_mode: str | None = None
    on_exceed: str | None = None
    organization: BudgetLevelConfig | None = None
    org: BudgetLevelConfig | None = None
    teams: dict[str, BudgetLevelConfig] | None = None
    users: dict[str, BudgetLevelConfig] | None = None
    keys: dict[str, BudgetLevelConfig] | None = None
    tags: dict[str, BudgetLevelConfig] | None = None


class CustomPricing(GatewayAdminContractModel):
    input_per_mtok: float | None = None
    output_per_mtok: float | None = None


class CostTrackingConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    custom_pricing: dict[str, CustomPricing] | None = None


class IPACLConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    allow: list[str] | None = None
    deny: list[str] | None = None


class AlertRuleConfig(GatewayAdminContractModel):
    name: str | None = None
    metric: str | None = None
    condition: str | None = None
    threshold: float | None = None
    window: str | None = None
    cooldown: str | None = None
    channels: list[str] | None = None


class AlertChannelConfig(GatewayAdminContractModel):
    name: str | None = None
    type: str | None = None
    url: str | None = None
    headers: dict[str, str] | None = None


class AlertingConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    rules: list[AlertRuleConfig] | None = None
    channels: list[AlertChannelConfig] | None = None


class RedactPatternConfig(GatewayAdminContractModel):
    name: str | None = None
    pattern: str | None = None


class PrivacyConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    mode: str | None = None
    redact_patterns: list[RedactPatternConfig] | None = None


class ToolPolicyConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    max_tools_per_request: int | None = None
    default_action: str | None = None
    allow: list[str] | None = None
    deny: list[str] | None = None


class MCPAuthOrgConfig(GatewayAdminContractModel):
    type: str | None = None
    token: str | None = None
    header: str | None = None
    key: str | None = None


class MCPServerOrgConfig(GatewayAdminContractModel):
    url: str | None = None
    transport: str | None = None
    auth: MCPAuthOrgConfig | None = None
    tools_cache_ttl: str | None = None


class MCPGuardrailOrgConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    blocked_tools: list[str] | None = None
    allowed_servers: list[str] | None = None
    validate_inputs: bool | None = None
    validate_outputs: bool | None = None
    tool_rate_limits: dict[str, int] | None = None


class MCPOrgConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    servers: dict[str, MCPServerOrgConfig] | None = None
    guardrails: MCPGuardrailOrgConfig | None = None


class AuditSinkConfig(GatewayAdminContractModel):
    type: str | None = None
    path: str | None = None
    url: str | None = None
    headers: dict[str, str] | None = None


class AuditOrgConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    min_severity: str | None = None
    categories: list[str] | None = None
    sinks: list[AuditSinkConfig] | None = None


class A2ACardConfig(GatewayAdminContractModel):
    name: str | None = None
    description: str | None = None
    version: str | None = None


class A2AAuthConfig(GatewayAdminContractModel):
    type: str | None = None
    token: str | None = None
    header: str | None = None


class A2ASkillConfig(GatewayAdminContractModel):
    id: str | None = None
    name: str | None = None
    description: str | None = None


class A2AAgentConfig(GatewayAdminContractModel):
    url: str | None = None
    auth: A2AAuthConfig | None = None
    description: str | None = None
    skills: list[A2ASkillConfig] | None = None


class A2AOrgConfig(GatewayAdminContractModel):
    enabled: bool | None = None
    card: A2ACardConfig | None = None
    agents: dict[str, A2AAgentConfig] | None = None


class PricingOverrideOrg(GatewayAdminContractModel):
    input_per_token: float | None = None
    output_per_token: float | None = None
    cached_input_per_token: float | None = None
    batch_input_per_token: float | None = None
    batch_output_per_token: float | None = None


class CapabilityOverrideOrg(GatewayAdminContractModel):
    function_calling: bool | None = None
    parallel_tool_calls: bool | None = None
    vision: bool | None = None
    audio_input: bool | None = None
    audio_output: bool | None = None
    pdf_input: bool | None = None
    streaming: bool | None = None
    response_schema: bool | None = None
    system_messages: bool | None = None
    prompt_caching: bool | None = None
    reasoning: bool | None = None


class ModelOverrideOrgConfig(GatewayAdminContractModel):
    max_input_tokens: int | None = None
    max_output_tokens: int | None = None
    pricing: PricingOverrideOrg | None = None
    capabilities: CapabilityOverrideOrg | None = None


class ModelDatabaseOrgConfig(GatewayAdminContractModel):
    overrides: dict[str, ModelOverrideOrgConfig] | None = None


class OrgConfig(GatewayAdminContractModel):
    providers: dict[str, ProviderConfig] | None = None
    guardrails: GuardrailConfig | None = None
    routing: RoutingConfig | None = None
    cache: CacheConfig | None = None
    rate_limiting: RateLimitConfig | None = None
    budgets: BudgetsConfig | None = None
    cost_tracking: CostTrackingConfig | None = None
    ip_acl: IPACLConfig | None = None
    alerting: AlertingConfig | None = None
    privacy: PrivacyConfig | None = None
    tool_policy: ToolPolicyConfig | None = None
    mcp: MCPOrgConfig | None = None
    audit: AuditOrgConfig | None = None
    a2a: A2AOrgConfig | None = None
    model_database: ModelDatabaseOrgConfig | None = None
    model_map: dict[str, str] | None = None


class CreateKeyRequest(GatewayAdminContractModel):
    name: str = ...
    owner: str | None = None
    models: list[str] | None = None
    providers: list[str] | None = None
    metadata: dict[str, str] | None = None


class UpdateKeyRequest(GatewayAdminContractModel):
    name: str | None = None
    owner: str | None = None
    models: list[str] | None = None
    providers: list[str] | None = None
    metadata: dict[str, str] | None = None


class KeyResponse(GatewayAdminContractModel):
    id: str | None = None
    key: str | None = None
    key_prefix: str | None = None
    name: str | None = None
    owner: str | None = None
    status: str | None = None
    key_type: str | None = None
    models: list[str] | None = None
    providers: list[str] | None = None
    allowed_models: list[str] | None = None
    allowed_providers: list[str] | None = None
    metadata: dict[str, str] | None = None
    created_at: str | None = None
    updated_at: str | None = None
    last_used_at: str | None = None
    credit_balance: float | None = None


class KeyListResponse(GatewayAdminContractModel):
    object: str | None = None
    data: list[KeyResponse] | None = None


class StatusResponse(GatewayAdminContractModel):
    status: str | None = None
    org_id: str | None = None
    deleted: bool | None = None
    loaded: int | None = None


class OrgConfigListResponse(GatewayAdminContractModel):
    object: str | None = None
    count: int | None = None
    data: dict[str, OrgConfig] | None = None
