STATIC_ROUTE_KEYS = (
    "home",
    "get_started",
    "workspace_list",
    "choose_goal",
    "observe_setup",
    "observe_project",
    "observe_send_first_trace",
    "observe_create_trace_evaluator",
    "observe_trace_detail",
    "observe_dashboard",
    "sample_trace",
    "support",
    "daily_quality_home",
    "prompt_workbench",
    "prompt_create",
    "prompt_run_test",
    "prompt_save_version",
    "prompt_compare_versions",
    "prompt_add_failure",
    "prompt_metrics",
    "agent_list",
    "agent_create",
    "agent_add_node",
    "agent_run_scenario",
    "agent_review_trace",
    "agent_save_eval",
    "agent_create_eval",
    "agent_quality",
    "gateway_overview",
    "gateway_provider",
    "gateway_key",
    "gateway_request",
    "gateway_log_review",
    "gateway_failure",
    "gateway_policy",
    "eval_list",
    "eval_create_data",
    "eval_add_scorer",
    "eval_run_first",
    "eval_review_failures",
    "eval_next_loop",
    "voice_list",
    "voice_create_agent",
    "voice_run_test_call",
    "voice_review_call",
    "voice_add_success_criteria",
    "voice_monitor_calls",
)


def route_keys_for_paths(paths):
    return frozenset((*STATIC_ROUTE_KEYS, *(f"path_{path}" for path in paths)))
