# Generated by Django 5.1.8 on 2026-07-06 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0020_reseed_broken_demo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceBook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('gallica_ark', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_books', to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_books', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Source Book',
                'verbose_name_plural': 'Source Books',
                'db_table': 'sources_source_book',
            },
        ),
        migrations.CreateModel(
            name='ScanPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField()),
                ('page_label', models.CharField(blank=True, default='', max_length=50)),
                ('iiif_url', models.URLField(blank=True, default='')),
                ('raw_ocr_text', models.TextField(blank=True, default='')),
                ('ocr_metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_pages', to='accounts.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_pages', to='accounts.workspace')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sources.sourcebook')),
            ],
            options={
                'verbose_name': 'Scan Page',
                'verbose_name_plural': 'Scan Pages',
                'db_table': 'sources_scan_page',
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='TargetPassage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_content', models.TextField()),
                ('modernized_text', models.TextField(blank=True, default='')),
                ('line_range', models.CharField(blank=True, default='', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_passages', to='accounts.organization')),
                ('scan_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to='sources.scanpage')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_passages', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Target Passage',
                'verbose_name_plural': 'Target Passages',
                'db_table': 'sources_target_passage',
            },
        ),
    ]
