# Generated by Django 5.1.8 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saml2_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="samlmetadatamodel",
            name="security_generation",
            field=models.IntegerField(default=1),
        ),
    ]
