# Generated by Django 5.1.8 on 2026-10-03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("saml2_auth", "0002_idp_generation"),
    ]

    operations = [
        migrations.CreateModel(
            name="SamlLoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relay_key", models.CharField(max_length=64, unique=True)),
                ("request_id", models.CharField(max_length=128, unique=True)),
                ("binder_hash", models.CharField(max_length=64)),
                ("next_path", models.CharField(max_length=512)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("consumed", "Consumed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "idp_meta_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("idp_generation", models.IntegerField(default=1)),
                ("candidate_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "deny_reason",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "idp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saml2_auth.samlmetadatamodel",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "user_hint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saml_login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "saml_login_attempt"},
        ),
        migrations.CreateModel(
            name="SamlResponseCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("candidate_key", models.CharField(max_length=64, unique=True)),
                ("payload", models.BinaryField()),
                ("payload_bytes", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saml2_auth.samlloginattempt",
                    ),
                ),
            ],
            options={"db_table": "saml_response_candidate"},
        ),
        migrations.AddIndex(
            model_name="samlloginattempt",
            index=models.Index(
                fields=["state", "expires_at"], name="saml_login__state_e04bff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="samlloginattempt",
            index=models.Index(
                fields=["user_hint", "created_at"],
                name="saml_login__user_hi_fee970_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="samlloginattempt",
            index=models.Index(
                fields=["expires_at"], name="saml_login__expires_429520_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="samlresponsecandidate",
            index=models.Index(
                fields=["attempt", "expires_at"], name="saml_respon_attempt_a99294_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="samlresponsecandidate",
            index=models.Index(
                fields=["expires_at"], name="saml_respon_expires_57bc03_idx"
            ),
        ),
    ]
