from rest_framework import serializers

from model_hub.models.ai_model import AIModel
from tracer.models.project import PROJECT_TYPES, Project, ProjectSourceChoices
from tracer.serializers.filters import (
    JsonValueField,
    MetricSortParamListField,
    ObserveGraphMetricConfigField,
    StrictInputSerializer,
    filter_list_field,
    filter_list_query_param_field,
)

# Pre-computed choice lists used in help_text so the LLM sees valid values inline.
_MODEL_TYPE_VALUES = [c[0] for c in AIModel.ModelTypes.choices]
_TRACE_TYPE_VALUES = [c[0] for c in PROJECT_TYPES]
_SOURCE_VALUES = [c[0] for c in ProjectSourceChoices.get_choices()]


class ProjectSerializer(serializers.ModelSerializer):
    """A project is a container for traces (observe) or evaluation runs (experiment).

    Each project belongs to an organization and (optionally) a workspace.
    Names must be unique per (organization, trace_type) pair.
    """

    id = serializers.UUIDField(
        read_only=True,
        help_text=(
            "Unique project identifier. UUID v4 format. "
            "Example: '550e8400-e29b-41d4-a716-446655440000'. "
            "**How to get it:** call `list_projects` to discover project IDs "
            "(optionally filter by 'name' query param to find a specific project). "
            "Do NOT pass the project name here — use the UUID."
        ),
    )
    name = serializers.CharField(
        max_length=255,
        help_text=(
            "Human-readable project name. Must be unique within the organization "
            "for a given trace_type. Use kebab-case or descriptive phrases. "
            "Examples: 'production-chat-bot', 'eval-summarization-v2', "
            "'rag-pipeline-staging'. Max 255 chars."
        ),
    )
    trace_type = serializers.ChoiceField(
        choices=PROJECT_TYPES,
        help_text=(
            f"Project category. One of: {_TRACE_TYPE_VALUES}. "
            "Use 'observe' for live production tracing of LLM apps; "
            "use 'experiment' for offline evaluation runs against datasets. "
            "Example: 'observe' for a chatbot in production, "
            "'experiment' for running evals on a prompt change."
        ),
    )
    model_type = serializers.ChoiceField(
        choices=AIModel.ModelTypes.choices,
        help_text=(
            f"Type of AI model the project tracks. Must be one of: {_MODEL_TYPE_VALUES}. "
            "Use 'GenerativeLLM' for chat/completion LLMs (GPT, Claude, Llama, etc.), "
            "'GenerativeImage' for image generation, 'TTS' for text-to-speech, "
            "'STT' for speech-to-text, 'MultiModal' for vision-language models, "
            "or one of the classical-ML types (Numeric, BinaryClassification, etc.) "
            "for traditional model evaluation. Default for most LLM apps: 'GenerativeLLM'."
        ),
    )
    metadata = serializers.JSONField(
        required=False,
        allow_null=True,
        help_text=(
            "Free-form metadata object for storing arbitrary project attributes. "
            "Use for environment info, owner team, deployment region, etc. "
            "Example: {'team': 'platform', 'env': 'staging', 'owner': 'kartik'}."
        ),
    )
    organization = serializers.UUIDField(
        read_only=True,
        help_text="Organization UUID. Auto-set from the authenticated user; cannot be overridden.",
    )
    workspace = serializers.UUIDField(
        read_only=True,
        help_text="Workspace UUID. Auto-set from the request context; cannot be overridden.",
    )
    created_at = serializers.DateTimeField(
        read_only=True,
        help_text="Project creation timestamp in ISO 8601 format (RFC 3339). "
        "Example: '2026-05-28T08:30:00Z'.",
    )
    updated_at = serializers.DateTimeField(
        read_only=True,
        help_text="Last modification timestamp in ISO 8601 format. Auto-updated on every save.",
    )
    source = serializers.ChoiceField(
        choices=ProjectSourceChoices.get_choices(),
        required=False,
        default=ProjectSourceChoices.PROTOTYPE.value,
        help_text=(
            f"How the project was created. One of: {_SOURCE_VALUES}. "
            "Use 'prototype' for normal user-created projects (default), "
            "'demo' for onboarding demo projects, "
            "'simulator' for projects auto-generated by agent simulation runs. "
            "Most LLM-created projects should use 'prototype'."
        ),
    )
    config = JsonValueField(
        required=False,
        allow_null=True,
        help_text=(
            "Trace column visibility configuration. List of objects with shape "
            "[{'id': 'column_name', 'is_visible': true}, ...]. Controls which "
            "trace fields appear in the dashboard. Leave null to use defaults."
        ),
    )
    session_config = JsonValueField(
        required=False,
        allow_null=True,
        help_text=(
            "Session view column visibility, same shape as 'config'. "
            "Controls which fields appear when viewing trace sessions in the dashboard."
        ),
    )
    tags = JsonValueField(
        required=False,
        allow_null=True,
        help_text=(
            "List of tag strings for organizing and filtering projects. "
            "Example: ['production', 'chatbot', 'v2']. Tags are case-sensitive. "
            "Used by list_projects for the 'tags' filter."
        ),
    )

    class Meta:
        model = Project
        fields = [
            "id",
            "model_type",
            "name",
            "trace_type",
            "metadata",
            "organization",
            "workspace",
            "created_at",
            "updated_at",
            "config",
            "source",
            "session_config",
            "tags",
        ]
        read_only_fields = ["organization", "workspace"]


class ProjectDetailResultSerializer(ProjectSerializer):
    sampling_rate = serializers.FloatField()

    class Meta(ProjectSerializer.Meta):
        fields = ProjectSerializer.Meta.fields + ["sampling_rate"]


class ProjectDetailResponseSerializer(serializers.Serializer):
    status = serializers.BooleanField(default=True)
    result = ProjectDetailResultSerializer()


class ProjectIdListItemSerializer(serializers.Serializer):
    id = serializers.UUIDField()
    name = serializers.CharField()
    trace_type = serializers.CharField()


class ProjectIdListResultSerializer(serializers.Serializer):
    projects = ProjectIdListItemSerializer(many=True)


class ProjectIdListResponseSerializer(serializers.Serializer):
    status = serializers.BooleanField(default=True)
    result = ProjectIdListResultSerializer()


class ProjectNameUpdateSerializer(serializers.Serializer):
    """Input for renaming a project and (optionally) adjusting its trace sampling rate.

    Use this when the user asks to "rename project X to Y" or
    "change sampling rate of project X to N%". Get the project_id first from list_projects.
    """

    project_id = serializers.UUIDField(
        required=True,
        help_text=(
            "UUID of the project to rename. "
            "**How to get it:** call `list_projects` first (optionally with the 'name' "
            "query param to narrow down) and copy the 'id' field from the returned "
            "project. UUID v4 format, e.g. '550e8400-e29b-41d4-a716-446655440000'. "
            "Do NOT pass the project name here — the API only accepts the UUID."
        ),
    )
    name = serializers.CharField(
        required=True,
        max_length=255,
        help_text=(
            "New project name. Must be unique within the organization for the "
            "same trace_type. Example: 'production-chat-bot-v3'. Max 255 chars. "
            "Cannot conflict with another existing project of the same trace_type."
        ),
    )
    sampling_rate = serializers.FloatField(
        required=False,
        min_value=0.0,
        max_value=100.0,
        help_text=(
            "Optional. Trace sampling rate. Accepts EITHER a fraction (0.0-1.0) or "
            "a percentage (1-100); values above 1 are treated as a percentage and "
            "normalized. Examples: 0.5 or 50 both = scan 50% of traces; 1.0 or 100 "
            "= scan all; 0.0 = scan none. Controls what fraction of ingested traces "
            "are run through evaluators. Default is 0.1 if not previously set. Omit "
            "to leave unchanged."
        ),
    )

    def validate_sampling_rate(self, value):
        # Stored model value is a 0.0-1.0 fraction (TraceScanConfig.sampling_rate),
        # but users and the UI think in percentages ("set sampling to 50"). Accept
        # both: values in (1, 100] are interpreted as a percentage (TH-5416).
        if value is None:
            return value
        if value > 1.0:
            value = value / 100.0
        return value


class ProjectVersionExportSerializer(StrictInputSerializer):
    project_id = serializers.UUIDField(required=True)
    runs_ids = serializers.ListField(
        child=serializers.UUIDField(), required=False, allow_null=True, default=list
    )
    filters = filter_list_field(required=False, default=list)
    sort_params = MetricSortParamListField(required=False, default=list)


class ProjectGraphDataQuerySerializer(StrictInputSerializer):
    project_id = serializers.UUIDField()
    interval = serializers.CharField(required=False, default="hour", allow_blank=False)
    filters = filter_list_query_param_field(required=False, default=list)


class ProjectUserMetricsRequestSerializer(StrictInputSerializer):
    end_user_id = serializers.UUIDField(
        help_text=(
            "UUID of the end user to fetch metrics for (the user_id hash "
            "from the project's Users table)."
        )
    )
    project_id = serializers.UUIDField(
        help_text="UUID of the observe project (from list_trace_projects)."
    )
    interval = serializers.CharField(
        required=False,
        default="day",
        allow_blank=False,
        help_text="Bucket size: hour, day (default), week, or month.",
    )
    filters = filter_list_field(required=False, default=list)


class ProjectUsersAggregateGraphDataRequestSerializer(StrictInputSerializer):
    project_id = serializers.UUIDField()
    interval = serializers.CharField(required=False, default="day", allow_blank=False)
    filters = filter_list_field(required=False, default=list)
    property = serializers.CharField(
        required=False, default="average", allow_blank=False
    )
    req_data_config = ObserveGraphMetricConfigField(required=False, default=dict)


class ProjectUserGraphDataQuerySerializer(StrictInputSerializer):
    project_id = serializers.UUIDField()
    end_user_id = serializers.UUIDField()


class ProjectUserGraphDataRequestSerializer(StrictInputSerializer):
    interval = serializers.CharField(required=False, default="hour", allow_blank=False)
    filters = filter_list_field(required=False, default=list)
