// Pre-flattened rows in the exact shape the My Environments table columns read.
// TODO(TH-7962): drop this fixture once Dileep's list endpoint lands and the
// query hook reads from axios instead.
export const MY_ENVIRONMENTS_FIXTURE = [
  {
    id: "env-support-line",
    name: "Customer Support Line",
    description: "Inbound refunds + order status over voice.",
    status: "passed",
    buildProgress: null,
    agentType: "voice",
    tools: 6,
    scenarios: 18,
    subgoals: 54,
    runsTotal: 3,
    runsPassed: 2,
    updatedAt: "2026-09-15T09:00:00Z",
  },
  {
    id: "env-billing-chat",
    name: "Billing Chat Agent",
    description: "Resolves invoice disputes and plan changes over chat.",
    status: "failed",
    buildProgress: null,
    agentType: "text",
    tools: 4,
    scenarios: 12,
    subgoals: 30,
    runsTotal: 5,
    runsPassed: 3,
    updatedAt: "2026-09-15T11:58:30Z",
  },
  {
    id: "env-repo-triage",
    name: "Repo Triage Bot",
    description: "Labels and routes incoming issues from the codebase.",
    status: "not_run",
    buildProgress: null,
    agentType: "code",
    tools: 9,
    scenarios: 22,
    subgoals: 61,
    runsTotal: 0,
    runsPassed: 0,
    updatedAt: "2026-09-13T12:00:00Z",
  },
  {
    id: "env-browser-checkout",
    name: "Browser Checkout Flow",
    description: "Completes a guest checkout across a multi-step cart.",
    status: "running",
    buildProgress: null,
    agentType: "computer",
    tools: 7,
    scenarios: 15,
    subgoals: 40,
    runsTotal: 2,
    runsPassed: 1,
    updatedAt: "2026-09-15T11:59:50Z",
  },
  {
    id: "env-airline-rebook",
    name: "Airline Rebooking",
    description: "Rebooks disrupted itineraries and issues credits.",
    status: "completed",
    buildProgress: null,
    agentType: "voice",
    tools: 11,
    scenarios: 27,
    subgoals: 88,
    runsTotal: 4,
    runsPassed: 4,
    updatedAt: "2026-08-01T12:00:00Z",
  },
  {
    id: "env-onboarding-build",
    name: "Onboarding Assistant",
    description: "Walks new users through first-run setup over chat.",
    status: "building",
    buildProgress: { done: 2, total: 5 },
    agentType: "text",
    tools: 3,
    scenarios: 8,
    subgoals: 19,
    runsTotal: 0,
    runsPassed: 0,
    updatedAt: "2026-09-14T12:00:00Z",
  },
];
