# Generated by Django 5.1.8 on 2026-06-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0074_canonicalize_simulate_eval_config_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentpromptoptimiserrun',
            name='optimiser_type',
            field=models.CharField(choices=[('random_search', 'Random Search'), ('gepa', 'GEPA'), ('protegi', 'Protegi'), ('bayesian', 'Bayesian'), ('metaprompt', 'Metaprompt'), ('promptwizard', 'PromptWizard'), ('agent_learning_kit', 'Agent Learning Kit')], max_length=50),
        ),
    ]
