# Generated by Django 5.1.8 on 2026-08-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulate", "0077_relax_simulate_eval_config_model_choices"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="scenarios",
            constraint=models.UniqueConstraint(
                models.functions.Lower("name"),
                "organization",
                condition=models.Q(("deleted", False)),
                name="unique_scenario_name_per_org",
            ),
        ),
    ]
