# Generated by Django 5.1.8 on 2026-08-25 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_sosloginproxy'),
        ('simulate', '0078_agentdefinition_target_speaks_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedHarnessAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('token_hash', models.CharField(max_length=64)),
                ('fence_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('registered', 'Registered'), ('provisioning', 'Provisioning'), ('running', 'Running'), ('finalizing', 'Finalizing'), ('cleaning_up', 'Cleaning up'), ('superseded', 'Superseded'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='registered', max_length=32)),
                ('event_watermark', models.PositiveBigIntegerField(default=0)),
                ('gap_started_at', models.DateTimeField(blank=True, null=True)),
                ('released_event_gaps', models.JSONField(default=list)),
                ('terminal_stage', models.CharField(blank=True, max_length=16, null=True)),
                ('terminal_reason', models.CharField(blank=True, max_length=32, null=True)),
                ('terminal_failure', models.JSONField(blank=True, null=True)),
                ('terminal_event_received', models.BooleanField(default=False)),
                ('manifest_acked', models.BooleanField(default=False)),
                ('provider_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('snapshot_name', models.CharField(blank=True, max_length=255, null=True)),
                ('snapshot_digest', models.CharField(blank=True, max_length=71, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'simulate_hosted_harness_attempt',
            },
        ),
        migrations.CreateModel(
            name='HostedHarnessCleanupReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_ref', models.CharField(max_length=255)),
                ('verified_absent', models.BooleanField()),
                ('details', models.JSONField(default=dict)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_receipt', to='simulate.hostedharnessattempt')),
            ],
            options={
                'db_table': 'simulate_hosted_harness_cleanup_receipt',
            },
        ),
        migrations.CreateModel(
            name='HostedHarnessJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(unique=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_digest', models.CharField(max_length=71)),
                ('schema_version', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('state', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('admitted', 'Admitted'), ('provisioning', 'Provisioning'), ('running', 'Running'), ('finalizing', 'Finalizing'), ('cleaning_up', 'Cleaning up'), ('retry_wait', 'Retry wait'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='received', max_length=32)),
                ('current_stage', models.CharField(default='queued', max_length=64)),
                ('current_attempt_number', models.PositiveIntegerField(default=0)),
                ('seed', models.BigIntegerField()),
                ('scenario_count', models.PositiveSmallIntegerField()),
                ('completed_count', models.PositiveSmallIntegerField(default=0)),
                ('failed_count', models.PositiveSmallIntegerField(default=0)),
                ('artifact_level', models.CharField(max_length=32)),
                ('max_artifact_bytes', models.BigIntegerField()),
                ('uploaded_artifact_bytes', models.BigIntegerField(default=0)),
                ('deadline_at', models.DateTimeField()),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=32, null=True)),
                ('terminal_at', models.DateTimeField(blank=True, null=True)),
                ('failure', models.JSONField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_harness_jobs', to='accounts.organization')),
                ('run_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_harness_jobs', to='simulate.runtest')),
                ('test_execution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_harness_job', to='simulate.testexecution')),
            ],
            options={
                'db_table': 'simulate_hosted_harness_job',
            },
        ),
        migrations.AddField(
            model_name='hostedharnessattempt',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='simulate.hostedharnessjob'),
        ),
        migrations.CreateModel(
            name='HostedHarnessArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=32)),
                ('size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=1024)),
                ('scenario_key', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='simulate.hostedharnessjob')),
            ],
            options={
                'db_table': 'simulate_hosted_harness_artifact',
            },
        ),
        migrations.CreateModel(
            name='HostedHarnessManifest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest', models.CharField(max_length=71)),
                ('complete', models.BooleanField()),
                ('body', models.JSONField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='simulate.hostedharnessattempt')),
            ],
            options={
                'db_table': 'simulate_hosted_harness_manifest',
            },
        ),
        migrations.CreateModel(
            name='HostedHarnessScenario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_key', models.CharField(max_length=255)),
                ('call_execution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_registration', to='simulate.callexecution')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_registrations', to='simulate.hostedharnessjob')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_registrations', to='simulate.scenarios')),
            ],
            options={
                'db_table': 'simulate_hosted_harness_scenario',
            },
        ),
        migrations.CreateModel(
            name='HostedHarnessReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('digest', models.CharField(max_length=71)),
                ('status', models.CharField(max_length=16)),
                ('body', models.JSONField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_receipts', to='simulate.hostedharnessattempt')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_receipts', to='simulate.hostedharnessjob')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='simulate.hostedharnessscenario')),
            ],
            options={
                'db_table': 'simulate_hosted_harness_receipt',
            },
        ),
        migrations.CreateModel(
            name='HostedHarnessSecret',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1', max_length=255)),
                ('encrypted_value', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_harness_secrets', to='accounts.organization')),
            ],
            options={
                'db_table': 'simulate_hosted_harness_secret',
            },
        ),
        migrations.CreateModel(
            name='HostedHarnessEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('stage', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('digest', models.CharField(max_length=71)),
                ('emitted_at', models.DateTimeField()),
                ('accepted', models.BooleanField(default=True)),
                ('rejection_code', models.CharField(blank=True, max_length=64, null=True)),
                ('rejection_message', models.CharField(blank=True, max_length=500, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulate.hostedharnessattempt')),
            ],
            options={
                'db_table': 'simulate_hosted_harness_event',
                'indexes': [models.Index(fields=['attempt', 'sequence'], name='idx_hevent_attempt_seq')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'sequence'), name='uniq_harness_event_sequence')],
            },
        ),
        migrations.AddIndex(
            model_name='hostedharnessjob',
            index=models.Index(fields=['organization', 'state'], name='idx_hjob_org_state'),
        ),
        migrations.AddIndex(
            model_name='hostedharnessjob',
            index=models.Index(fields=['state', 'deadline_at'], name='idx_hjob_state_deadline'),
        ),
        migrations.AddConstraint(
            model_name='hostedharnessjob',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_harness_job_org_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='hostedharnessjob',
            constraint=models.CheckConstraint(condition=models.Q(('scenario_count__gte', 1), ('scenario_count__lte', 10)), name='harness_job_scenario_count_1_10'),
        ),
        migrations.AddIndex(
            model_name='hostedharnessattempt',
            index=models.Index(fields=['job', 'state'], name='idx_hattempt_job_state'),
        ),
        migrations.AddIndex(
            model_name='hostedharnessattempt',
            index=models.Index(fields=['state', 'expires_at'], name='idx_hattempt_expiry'),
        ),
        migrations.AddConstraint(
            model_name='hostedharnessattempt',
            constraint=models.UniqueConstraint(fields=('job', 'attempt_number'), name='uniq_harness_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='hostedharnessartifact',
            constraint=models.UniqueConstraint(fields=('job', 'sha256'), name='uniq_harness_job_artifact'),
        ),
        migrations.AddConstraint(
            model_name='hostedharnessmanifest',
            constraint=models.UniqueConstraint(fields=('attempt', 'digest'), name='uniq_harness_attempt_manifest'),
        ),
        migrations.AddConstraint(
            model_name='hostedharnessscenario',
            constraint=models.UniqueConstraint(fields=('job', 'scenario_key'), name='uniq_harness_scenario_key'),
        ),
        migrations.AddConstraint(
            model_name='hostedharnessreceipt',
            constraint=models.UniqueConstraint(fields=('job', 'scenario'), name='uniq_harness_job_scenario_receipt'),
        ),
        migrations.AddConstraint(
            model_name='hostedharnesssecret',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'version'), name='uniq_harness_secret_version'),
        ),
    ]
