# Generated by Django 5.1.8 on 2026-08-19 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0122_backfill_queueitem_source_preview'),
        ('simulate', '0078_agentdefinition_target_speaks_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulateevalconfig',
            name='pinned_version',
            field=models.ForeignKey(blank=True, help_text='Pin to a specific template version for runtime.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_simulate_eval_configs', to='model_hub.evaltemplateversion'),
        ),
    ]
