# Generated by Django 5.1.8 on 2026-08-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0079_harness_environment_credentials'),
        ('simulate', '0079_hosted_harness_channels'),
    ]

    operations = [
    ]
