# Generated by Django 5.1.8 on 2026-08-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0081_simulateevalconfig_uniq_simulate_eval_config_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rlscenario',
            name='max_turns',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of turns allowed'),
        ),
        migrations.AlterField(
            model_name='rlscenario',
            name='solution',
            field=models.JSONField(blank=True, default=list, help_text='Reference solution'),
        ),
        migrations.AlterField(
            model_name='rlworld',
            name='world_checks',
            field=models.JSONField(blank=True, default=dict, help_text='World-level checks'),
        ),
    ]
