# Generated by Django 5.1.8 on 2026-08-21 09:05

from django.db import migrations, models


def _normalize_rl_json_shapes(apps, schema_editor):
    # A DB that already applied 0079-0081 (a teammate's pull, before the shape
    # corrections landed) may still hold rows in the old list/dict shapes;
    # Phase 3 code reading these as the new shape would crash on them.
    RLWorld = apps.get_model("simulate", "RLWorld")
    RLScenario = apps.get_model("simulate", "RLScenario")

    for world in RLWorld.objects.all().iterator():
        if isinstance(world.world_checks, list):
            world.world_checks = {}
            world.save(update_fields=["world_checks"])

    for scenario in RLScenario.objects.all().iterator():
        update_fields = []
        if isinstance(scenario.checks, list):
            scenario.checks = {}
            update_fields.append("checks")
        if isinstance(scenario.solution, dict):
            scenario.solution = []
            update_fields.append("solution")
        if update_fields:
            scenario.save(update_fields=update_fields)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0082_alter_rlscenario_max_turns_alter_rlscenario_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rlworldcopy',
            name='state',
            field=models.JSONField(blank=True, default=dict, help_text="The copy's live, mutated state"),
        ),
        migrations.AlterField(
            model_name='rlscenario',
            name='checks',
            field=models.JSONField(blank=True, default=dict, help_text='Scenario-level checks'),
        ),
        migrations.RunPython(_normalize_rl_json_shapes, _noop),
    ]
