# Generated by Django 5.1.8 on 2026-08-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0085_hostedharnessscenario_dataset_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedharnessattempt',
            name='effective_parallelism',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedharnessattempt',
            name='degrade_reasons',
            field=models.JSONField(default=list),
        ),
    ]
