# Generated by Django 5.1.8 on 2026-09-16 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0025_gcpmarketplaceprocessedevent_gcpmarketplaceaccount_and_more",
        ),
        ("simulate", "0086_hostedharnessattempt_diagnostics"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostedHarnessConversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("cold", "Cold"),
                            ("starting", "Starting"),
                            ("hydrating", "Hydrating"),
                            ("warm_idle", "Warm idle"),
                            ("responding", "Responding"),
                            ("waiting_for_user", "Waiting for user"),
                            ("degraded", "Degraded"),
                            ("retired", "Retired"),
                        ],
                        default="cold",
                        max_length=32,
                    ),
                ),
                ("current_stage", models.CharField(default="reception", max_length=32)),
                ("next_message_sequence", models.PositiveBigIntegerField(default=1)),
                ("next_event_sequence", models.PositiveBigIntegerField(default=1)),
                ("command_acked_through", models.PositiveBigIntegerField(default=0)),
                ("event_acked_through", models.PositiveBigIntegerField(default=0)),
                (
                    "active_invocation_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("blocking_input", models.JSONField(blank=True, null=True)),
                ("policy_hash", models.CharField(default="", max_length=64)),
                (
                    "latest_workspace_digest",
                    models.CharField(blank=True, max_length=71, null=True),
                ),
                (
                    "latest_scenario_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "latest_workspace_object_key",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("last_activity_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation",
                        to="simulate.hostedharnessjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_harness_conversations",
                        to="accounts.organization",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_harness_conversations",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "simulate_hosted_harness_conversation",
            },
        ),
        migrations.CreateModel(
            name="HostedHarnessConversationEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                ("kind", models.CharField(max_length=64)),
                ("message_id", models.UUIDField(blank=True, null=True)),
                ("stage", models.CharField(default="", max_length=32)),
                (
                    "invocation_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "function_call_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payload", models.JSONField(default=dict)),
                ("digest", models.CharField(max_length=71)),
                ("emitted_at", models.DateTimeField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="simulate.hostedharnessconversation",
                    ),
                ),
            ],
            options={
                "db_table": "simulate_hosted_harness_conversation_event",
            },
        ),
        migrations.CreateModel(
            name="HostedHarnessConversationLease",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_ref", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("starting", "Starting"),
                            ("active", "Active"),
                            ("draining", "Draining"),
                            ("expired", "Expired"),
                            ("released", "Released"),
                        ],
                        default="starting",
                        max_length=16,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64)),
                ("fence_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("command_watermark", models.PositiveBigIntegerField(default=0)),
                ("event_watermark", models.PositiveBigIntegerField(default=0)),
                ("snapshot_name", models.CharField(default="", max_length=255)),
                ("snapshot_digest", models.CharField(default="", max_length=71)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_leases",
                        to="simulate.hostedharnessattempt",
                    ),
                ),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease",
                        to="simulate.hostedharnessconversation",
                    ),
                ),
            ],
            options={
                "db_table": "simulate_hosted_harness_conversation_lease",
            },
        ),
        migrations.CreateModel(
            name="HostedHarnessConversationMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_request_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("message", "Message"),
                            ("question", "Question"),
                            ("confirmation", "Confirmation"),
                            ("status", "Status"),
                        ],
                        default="message",
                        max_length=24,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("delivered", "Delivered"),
                            ("streaming", "Streaming"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("stage", models.CharField(default="", max_length=32)),
                ("content", models.TextField(default="")),
                ("payload", models.JSONField(default=dict)),
                (
                    "invocation_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "function_call_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reply_to", models.UUIDField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="simulate.hostedharnessconversation",
                    ),
                ),
            ],
            options={
                "db_table": "simulate_hosted_harness_conversation_message",
            },
        ),
        migrations.AddIndex(
            model_name="hostedharnessconversation",
            index=models.Index(
                fields=["organization", "state"], name="idx_hconv_org_state"
            ),
        ),
        migrations.AddIndex(
            model_name="hostedharnessconversation",
            index=models.Index(
                fields=["state", "last_activity_at"], name="idx_hconv_state_seen"
            ),
        ),
        migrations.AddIndex(
            model_name="hostedharnessconversationevent",
            index=models.Index(
                fields=["conversation", "sequence"], name="idx_hconv_evt_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="hostedharnessconversationevent",
            constraint=models.UniqueConstraint(
                fields=("conversation", "sequence"), name="uniq_hconv_event_sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="hostedharnessconversationlease",
            index=models.Index(
                fields=["state", "expires_at"], name="idx_hconv_lease_exp"
            ),
        ),
        migrations.AddIndex(
            model_name="hostedharnessconversationmessage",
            index=models.Index(
                fields=["conversation", "sequence"], name="idx_hconv_msg_sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="hostedharnessconversationmessage",
            index=models.Index(
                fields=["conversation", "state"], name="idx_hconv_msg_state"
            ),
        ),
        migrations.AddConstraint(
            model_name="hostedharnessconversationmessage",
            constraint=models.UniqueConstraint(
                fields=("conversation", "sequence"), name="uniq_hconv_message_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="hostedharnessconversationmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_request_id__isnull", False)),
                fields=("conversation", "client_request_id"),
                name="uniq_hconv_client_request",
            ),
        ),
    ]
