# Generated by Django 5.1.8 on 2026-09-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulate", "0089_hosted_harness_conversation_transcript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostedharnessconversationtranscript",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
