# Generated by Django 5.2

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("simulate", "0091_merge_hosted_harness_dev")]

    operations = [
        migrations.AddField(
            model_name="hostedharnessjob",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                help_text="Authored environment reused by this simulation-only job",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulation_runs",
                to="simulate.hostedharnessjob",
            ),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="trials",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Requested executions of each selected authored scenario",
            ),
        ),
        migrations.CreateModel(
            name="HostedHarnessExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("execution_key", models.CharField(max_length=255)),
                ("trial_index", models.PositiveSmallIntegerField()),
                (
                    "call_execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_harness_execution",
                        to="simulate.callexecution",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenario_executions",
                        to="simulate.hostedharnessjob",
                    ),
                ),
                (
                    "source_scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="simulate.hostedharnessscenario",
                    ),
                ),
            ],
            options={"db_table": "simulate_hosted_harness_execution"},
        ),
        migrations.AddConstraint(
            model_name="hostedharnessexecution",
            constraint=models.UniqueConstraint(
                fields=("job", "execution_key"),
                name="uniq_harness_job_execution_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="hostedharnessexecution",
            constraint=models.UniqueConstraint(
                fields=("job", "source_scenario", "trial_index"),
                name="uniq_harness_job_scenario_trial",
            ),
        ),
        migrations.AddField(
            model_name="hostedharnessreceipt",
            name="execution",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="simulate.hostedharnessexecution",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="hostedharnessreceipt",
            name="uniq_harness_job_scenario_receipt",
        ),
        migrations.AddConstraint(
            model_name="hostedharnessreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("execution__isnull", False)),
                fields=("job", "execution"),
                name="uniq_harness_job_execution_receipt",
            ),
        ),
        migrations.AddConstraint(
            model_name="hostedharnessreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("execution__isnull", True)),
                fields=("job", "scenario"),
                name="uniq_harness_legacy_scenario_receipt",
            ),
        ),
    ]
