# Generated by Django 5.1.8 on 2026-10-05 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_gcpmarketplaceprocessedevent_gcpmarketplaceaccount_and_more'),
        ('simulate', '0097_merge_selected_runs_environment_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedharnessjob',
            name='template_slug',
            field=models.SlugField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='hostedharnessjob',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_harness_jobs', to='accounts.organization'),
        ),
        migrations.AddConstraint(
            model_name='hostedharnessjob',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('template_slug',), name='uniq_harness_system_template_slug'),
        ),
        migrations.AddConstraint(
            model_name='hostedharnessjob',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False), models.Q(('template_slug', ''), _negated=True), _connector='OR'), name='harness_job_orgless_is_template'),
        ),
    ]
