# Generated by Django 5.1.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_playground", "0011_alter_prompttemplatenode_prompt_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="max_concurrent_nodes",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum number of this agent's nodes that may run at the same time.",
            ),
        ),
    ]
