# Generated by Django 5.1.8 on 2026-09-03 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_sosloginproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPMarketplaceProcessedEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('subject_id', models.CharField(blank=True, db_index=True, help_text='Entitlement or account id the event is about, taken from the message body.', max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GCP Marketplace Processed Event',
                'verbose_name_plural': 'GCP Marketplace Processed Events',
                'db_table': 'gcp_marketplace_processed_event',
            },
        ),
        migrations.CreateModel(
            name='GCPMarketplaceAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procurement_account_id', models.CharField(help_text='Bare account id, the last segment of the Google resource name.', max_length=255, unique=True)),
                ('google_user_identity', models.CharField(blank=True, db_index=True, help_text='Obfuscated Google user id from the sign-up token. Supplied once, at sign-up, and never retrievable afterwards.', max_length=255)),
                ('state', models.CharField(choices=[('ACCOUNT_STATE_UNSPECIFIED', 'Unspecified'), ('ACCOUNT_ACTIVATION_REQUESTED', 'Activation Requested'), ('ACCOUNT_ACTIVE', 'Active')], default='ACCOUNT_STATE_UNSPECIFIED', max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gcp_marketplace_account', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'GCP Marketplace Account',
                'verbose_name_plural': 'GCP Marketplace Accounts',
                'db_table': 'gcp_marketplace_account',
            },
        ),
        migrations.CreateModel(
            name='GCPMarketplaceEntitlement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entitlement_id', models.CharField(help_text='Bare entitlement id, the key every Pub/Sub event carries.', max_length=255, unique=True)),
                ('plan_id', models.CharField(blank=True, max_length=255)),
                ('new_pending_plan', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ENTITLEMENT_STATE_UNSPECIFIED', 'Unspecified'), ('ENTITLEMENT_ACTIVATION_REQUESTED', 'Activation Requested'), ('ENTITLEMENT_ACTIVE', 'Active'), ('ENTITLEMENT_PENDING_PLAN_CHANGE_APPROVAL', 'Pending Plan Change Approval'), ('ENTITLEMENT_PENDING_PLAN_CHANGE', 'Pending Plan Change'), ('ENTITLEMENT_PENDING_CANCELLATION', 'Pending Cancellation'), ('ENTITLEMENT_CANCELLED', 'Cancelled'), ('ENTITLEMENT_SUSPENDED', 'Suspended')], db_index=True, default='ENTITLEMENT_STATE_UNSPECIFIED', max_length=64)),
                ('usage_reporting_id', models.CharField(blank=True, help_text='consumerId for Service Control. Usage cannot be reported without it.', max_length=255)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('offer', models.CharField(blank=True, max_length=512)),
                ('offer_end_time', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('google_update_time', models.DateTimeField(blank=True, help_text='Entitlement updateTime. Discard events older than the stored value.', null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(blank=True, help_text='Null while an entitlement event arrives before sign-up completes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='accounts.gcpmarketplaceaccount')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gcp_marketplace_entitlements', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'GCP Marketplace Entitlement',
                'verbose_name_plural': 'GCP Marketplace Entitlements',
                'db_table': 'gcp_marketplace_entitlement',
            },
        ),
        migrations.CreateModel(
            name='GCPMarketplaceUsageCheckpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(max_length=255)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('quantity_reported', models.DecimalField(decimal_places=6, max_digits=24)),
                ('operation_id', models.CharField(help_text='Id sent with the report. Google documents no dedupe on it, so this table is what prevents a resend.', max_length=255)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('report_status', models.CharField(choices=[('pending', 'Pending'), ('reported', 'Reported'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_detail', models.TextField(blank=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_checkpoints', to='accounts.gcpmarketplaceentitlement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcp_marketplace_usage_checkpoints', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'GCP Marketplace Usage Checkpoint',
                'verbose_name_plural': 'GCP Marketplace Usage Checkpoints',
                'db_table': 'gcp_marketplace_usage_checkpoint',
                'constraints': [models.UniqueConstraint(fields=('entitlement', 'metric', 'window_start'), name='uq_gcp_mkt_usage_entitlement_metric_window')],
            },
        ),
    ]
