# Generated by Django 5.1.8 on 2026-10-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0025_gcpmarketplaceprocessedevent_gcpmarketplaceaccount_and_more",
        ),
        ("saml2_auth", "0003_login_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="authtoken",
            name="auth_origin",
            field=models.CharField(
                blank=True,
                choices=[("saml", "Saml")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="authtoken",
            name="origin_idp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saml_auth_tokens",
                to="saml2_auth.samlmetadatamodel",
            ),
        ),
        migrations.AddField(
            model_name="authtoken",
            name="origin_idp_generation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authtoken",
            name="scoped_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoped_auth_tokens",
                to="accounts.organization",
            ),
        ),
    ]
