"""Offline real-protocol fixtures; no PeerDB/ClickHouse/Django initialization."""

from copy import deepcopy
from unittest.mock import Mock

import pytest

from tracer.services.clickhouse.oss_cdc_inventory import (
    InventoryError,
    InventoryPending,
    PeerTarget,
    inspect_mappings,
)

SOURCE = PeerTarget("pg_source", "pg", 5432, "app")
DEST = PeerTarget("ch_dest", "ch", 9000, "catalog_app")

# Recorded from the isolated v0.36.9 mirror status, independently of the adapter.
RECORDED_ENV_DEFAULTS = {
    "PEERDB_CLICKHOUSE_CLIENT_NAME": "peerdb",
    "PEERDB_CLICKHOUSE_INITIAL_LOAD_ALLOW_NON_EMPTY_TABLES": "false",
    "PEERDB_FORCE_INTERNAL_VERSION": "4",
    "PEERDB_POSTGRES_WAL_SENDER_TIMEOUT": "120s",
    "PEERDB_SOURCE_SCHEMA_AS_DESTINATION_COLUMN": "false",
}


@pytest.fixture
def api():
    # Camel-case spelling and populated defaults independently captured from
    # local flow-api stable-v0.36.9, not generated by the production adapter.
    peers = {
        "pg_source": {
            "peer": {
                "name": "pg_source",
                "type": "POSTGRES",
                "postgresConfig": {
                    "host": "pg",
                    "port": 5432,
                    "database": "app",
                    "password": "do-not-log",
                },
            }
        },
        "ch_dest": {
            "peer": {
                "name": "ch_dest",
                "type": "CLICKHOUSE",
                "clickhouseConfig": {
                    "host": "ch",
                    "port": 9000,
                    "database": "catalog_app",
                    "password": "do-not-log",
                },
            }
        },
    }
    listing = {
        "mirrors": [
            {
                "name": "mirror_model_hub_score",
                "sourceName": "pg_source",
                "destinationName": "ch_dest",
                "sourceType": "POSTGRES",
                "destinationType": "CLICKHOUSE",
                "isCdc": True,
                "status": "STATUS_RUNNING",
            }
        ]
    }
    status = {
        "flowJobName": "mirror_model_hub_score",
        "currentFlowState": "STATUS_RUNNING",
        "cdcStatus": {
            "config": {
                "flowJobName": "mirror_model_hub_score",
                "sourceName": "pg_source",
                "destinationName": "ch_dest",
                "softDeleteColName": "_peerdb_is_deleted",
                "syncedAtColName": "_peerdb_synced_at",
                "resync": False,
                "initialSnapshotOnly": False,
                "doInitialSnapshot": False,
                "script": "",
                "system": "Q",
                "env": {},
                "flags": [],
                "version": 4,
                "tableMappings": [
                    {
                        "sourceTableIdentifier": "public.model_hub_score",
                        "destinationTableIdentifier": "model_hub_score",
                        "exclude": [],
                        "columns": [],
                        "partitionKey": "",
                        "shardingKey": "",
                        "policyName": "",
                        "partitionByExpr": "",
                        "engine": "CH_ENGINE_REPLACING_MERGE_TREE",
                    }
                ],
            }
        },
    }

    def request(method, path, payload):
        if method == "GET" and path.startswith("/v1/peers/info/"):
            assert payload is None
            return peers[path.removeprefix("/v1/peers/info/")]
        if method == "GET" and path == "/v1/mirrors/list":
            assert payload is None
            return listing
        assert (method, path, payload) == (
            "POST",
            "/v1/mirrors/status",
            {
                "flowJobName": "mirror_model_hub_score",
                "includeFlowInfo": True,
                "excludeBatches": True,
            },
        )
        return status

    return peers, listing, status, Mock(side_effect=request)


def inspect(api):
    return inspect_mappings(api[-1], source=SOURCE, destination=DEST)


def test_current_effective_mapping_and_read_only_routes(api):
    before = deepcopy(api[:3])
    assert inspect(api) == (("mirror_model_hub_score", "model_hub_score"),)
    assert api[-1].call_count == 4
    assert api[:3] == before  # no input configuration mutation


def test_successfully_inspected_empty_inventory_is_not_a_transport_failure(api):
    api[1]["mirrors"] = []
    assert inspect(api) == ()
    assert api[-1].call_count == 3


@pytest.mark.parametrize(
    "envelope", [{}, {"mirrors": None}, {"mirrors": {}}, {"mirrors": [None]}]
)
def test_missing_or_malformed_inventory_never_becomes_empty(api, envelope):
    api[1].clear()
    api[1].update(envelope)
    with pytest.raises(InventoryError):
        inspect(api)


@pytest.mark.parametrize(
    "error",
    [TimeoutError("secret-token"), ValueError("secret-token"), OSError("secret-token")],
)
def test_transport_json_and_timeout_errors_are_sanitized(api, error):
    api[-1].side_effect = error
    with pytest.raises(InventoryError) as exc:
        inspect(api)
    assert "secret-token" not in str(exc.value)
    assert exc.value.__suppress_context__


@pytest.mark.parametrize(
    "key,value",
    [("host", "foreign"), ("database", "foreign"), ("port", 9001), ("port", True)],
)
def test_peer_endpoint_must_match_configured_target(api, key, value):
    api[0]["ch_dest"]["peer"]["clickhouseConfig"][key] = value
    with pytest.raises(InventoryError):
        inspect(api)


@pytest.mark.parametrize(
    "key,value",
    [
        ("name", ""),
        ("destinationType", "POSTGRES"),
        ("sourceType", "CLICKHOUSE"),
        ("isCdc", False),
        ("isCdc", 1),
        ("status", "STATUS_PAUSED"),
    ],
)
def test_invalid_target_mirror_identity_or_state_is_rejected(api, key, value):
    api[1]["mirrors"][0][key] = value
    with pytest.raises(InventoryError):
        inspect(api)


def test_duplicate_mirror_names_are_rejected(api):
    api[1]["mirrors"].append(deepcopy(api[1]["mirrors"][0]))
    with pytest.raises(InventoryError, match="duplicate mirror"):
        inspect(api)


def test_unknown_peer_does_not_become_unrelated(api):
    api[1]["mirrors"][0]["destinationName"] = "unreadable"
    with pytest.raises(InventoryError, match="inspection failed"):
        inspect(api)


def test_same_target_alias_still_has_all_its_effective_mappings_checked(api):
    alias = deepcopy(api[0]["ch_dest"])
    alias["peer"]["name"] = "alias"
    api[0]["alias"] = alias
    api[1]["mirrors"][0]["destinationName"] = "alias"
    api[2]["cdcStatus"]["config"]["destinationName"] = "alias"
    assert inspect(api) == (("mirror_model_hub_score", "model_hub_score"),)


@pytest.mark.parametrize("kind", ["POSTGRES", "UNKNOWN_TYPE"])
def test_alias_with_contradictory_type_cannot_become_empty_inventory(api, kind):
    alias = deepcopy(api[0]["ch_dest"])
    alias["peer"]["name"] = "alias"
    api[0]["alias"] = alias
    api[1]["mirrors"][0].update(destinationName="alias", destinationType=kind)
    api[2]["cdcStatus"]["config"]["destinationName"] = "alias"
    with pytest.raises(InventoryError):
        inspect(api)


def test_verified_postgres_destination_can_be_ignored_without_status_request(api):
    api[1]["mirrors"][0].update(destinationName="pg_source", destinationType="POSTGRES")
    assert inspect(api) == ()
    assert api[-1].call_count == 3  # verified source peer is cached
    assert all(call.args[0] == "GET" for call in api[-1].call_args_list)


def test_unreadable_non_clickhouse_destination_is_not_assumed_unrelated(api):
    api[1]["mirrors"][0].update(
        destinationName="unreadable", destinationType="POSTGRES"
    )
    with pytest.raises(InventoryError, match="inspection failed"):
        inspect(api)


def test_unrelated_verified_endpoint_is_not_inspected_or_modified(api):
    other = deepcopy(api[0]["ch_dest"])
    other["peer"]["name"] = "other"
    other["peer"]["clickhouseConfig"]["database"] = "another_db"
    api[0]["other"] = other
    api[1]["mirrors"][0]["destinationName"] = "other"
    assert inspect(api) == ()
    assert all(call.args[0] == "GET" for call in api[-1].call_args_list)


@pytest.mark.parametrize(
    "key,value",
    [
        ("flowJobName", "other"),
        ("sourceName", "other"),
        ("destinationName", "other"),
        ("softDeleteColName", ""),
        ("syncedAtColName", ""),
        ("resync", True),
        ("initialSnapshotOnly", True),
        ("resync", 0),
        ("script", "transform"),
        ("system", "PG"),
        ("env", {"unknown": "do-not-log"}),
        ("flags", ["unqualified"]),
        ("tableMappings", []),
        ("tableMappings", None),
    ],
)
def test_effective_configuration_not_just_list_name_is_validated(api, key, value):
    api[2]["cdcStatus"]["config"][key] = value
    with pytest.raises(InventoryError):
        inspect(api)


@pytest.mark.parametrize("version", [0, 1, 4, 1000, None])
def test_no_operator_managed_numeric_revision_contract(api, version):
    api[2]["cdcStatus"]["config"]["version"] = version
    assert inspect(api) == (("mirror_model_hub_score", "model_hub_score"),)


@pytest.mark.parametrize(
    "env", [{}, {"PEERDB_NULLABLE": "true"}, {"PEERDB_NULLABLE": "false"}]
)
def test_known_nullable_setting_does_not_require_a_revision_contract(api, env):
    api[2]["cdcStatus"]["config"]["env"] = env
    before = deepcopy(api[:3])
    assert inspect(api) == (("mirror_model_hub_score", "model_hub_score"),)
    assert api[:3] == before  # inherited settings are not rewritten or inferred


@pytest.mark.parametrize("nullable", [None, "true", "false"])
@pytest.mark.parametrize(
    "defaults",
    [{key: value} for key, value in RECORDED_ENV_DEFAULTS.items()]
    + [RECORDED_ENV_DEFAULTS],
    ids=[*RECORDED_ENV_DEFAULTS, "full-recorded-env"],
)
def test_partial_and_full_recorded_transport_defaults_are_accepted(
    api, defaults, nullable
):
    env = dict(defaults)
    if nullable is not None:
        env["PEERDB_NULLABLE"] = nullable
    api[2]["cdcStatus"]["config"]["env"] = env
    before = deepcopy(api[:3])
    assert inspect(api) == (("mirror_model_hub_score", "model_hub_score"),)
    assert api[:3] == before


@pytest.mark.parametrize("version", [0, 1, 4, 1000, None])
def test_recorded_internal_version_is_not_an_operator_revision(api, version):
    api[2]["cdcStatus"]["config"].update(
        env={**RECORDED_ENV_DEFAULTS, "PEERDB_NULLABLE": "true"}, version=version
    )
    assert inspect(api) == (("mirror_model_hub_score", "model_hub_score"),)


@pytest.mark.parametrize(
    "key,value",
    [
        ("PEERDB_CLICKHOUSE_CLIENT_NAME", "other-client"),
        ("PEERDB_CLICKHOUSE_INITIAL_LOAD_ALLOW_NON_EMPTY_TABLES", "true"),
        ("PEERDB_FORCE_INTERNAL_VERSION", "3"),
        ("PEERDB_FORCE_INTERNAL_VERSION", "5"),
        ("PEERDB_POSTGRES_WAL_SENDER_TIMEOUT", "121s"),
        ("PEERDB_SOURCE_SCHEMA_AS_DESTINATION_COLUMN", "true"),
        ("PEERDB_NULLABLE", "TRUE"),
        ("unknown", "secret-transform"),
        (None, "secret-transform"),
        (4, "secret-transform"),
    ],
)
def test_recorded_transport_defaults_do_not_allow_other_values_or_keys(api, key, value):
    api[2]["cdcStatus"]["config"]["env"] = {
        **RECORDED_ENV_DEFAULTS,
        "PEERDB_NULLABLE": "true",
        key: value,
    }
    with pytest.raises(InventoryError, match="CDC settings") as error:
        inspect(api)
    assert "secret-transform" not in str(error.value)


@pytest.mark.parametrize("key", [*RECORDED_ENV_DEFAULTS, "PEERDB_NULLABLE"])
@pytest.mark.parametrize("value", [None, True, 4, [], {}])
def test_recorded_settings_require_string_values(api, key, value):
    api[2]["cdcStatus"]["config"]["env"] = {
        **RECORDED_ENV_DEFAULTS,
        "PEERDB_NULLABLE": "true",
        key: value,
    }
    with pytest.raises(InventoryError, match="CDC settings"):
        inspect(api)


@pytest.mark.parametrize(
    "env",
    [
        None,
        [],
        "",
        {"PEERDB_NULLABLE": True},
        {"PEERDB_NULLABLE": None},
        {"PEERDB_NULLABLE": ""},
        {"PEERDB_NULLABLE": "TRUE"},
        {"PEERDB_NULLABLE": "true", "unknown": "secret-transform"},
    ],
)
def test_malformed_or_unknown_mirror_settings_are_rejected(api, env):
    api[2]["cdcStatus"]["config"]["env"] = env
    with pytest.raises(InventoryError) as error:
        inspect(api)
    assert "secret-transform" not in str(error.value)


def test_missing_mirror_settings_are_not_assumed_inherited(api):
    del api[2]["cdcStatus"]["config"]["env"]
    with pytest.raises(InventoryError):
        inspect(api)


def test_snapshot_creation_intent_is_not_current_snapshot_state(api):
    api[2]["cdcStatus"]["config"]["doInitialSnapshot"] = True
    assert inspect(api)
    api[2]["currentFlowState"] = "STATUS_SNAPSHOT"
    with pytest.raises(InventoryError, match="stable running"):
        inspect(api)


@pytest.mark.parametrize("state", ["STATUS_SETUP", "STATUS_SNAPSHOT"])
@pytest.mark.parametrize("location", ["listing", "status", "both"])
def test_initial_snapshot_is_pollable_but_never_a_mapping(api, state, location):
    if location in ("listing", "both"):
        api[1]["mirrors"][0]["status"] = state
    if location in ("status", "both"):
        api[2]["currentFlowState"] = state
    with pytest.raises(InventoryPending):
        inspect(api)


@pytest.mark.parametrize(
    "state",
    [
        "STATUS_UNKNOWN",
        "STATUS_PAUSED",
        "STATUS_FAILED",
        "STATUS_RESYNC",
        "STATUS_MODIFYING",
        "STATUS_TERMINATED",
        "STATUS_COMPLETED",
        None,
        {},
    ],
)
def test_unqualified_state_is_not_a_retryable_snapshot(api, state):
    api[2]["currentFlowState"] = state
    with pytest.raises(InventoryError) as caught:
        inspect(api)
    assert not isinstance(caught.value, InventoryPending)


def test_wrong_status_identity_cannot_be_hidden_by_pending_state(api):
    api[2]["currentFlowState"] = "STATUS_SNAPSHOT"
    api[2]["flowJobName"] = "foreign-mirror"
    with pytest.raises(InventoryError) as caught:
        inspect(api)
    assert not isinstance(caught.value, InventoryPending)


@pytest.mark.parametrize(
    "key,value",
    [
        ("sourceTableIdentifier", "foreign.model_hub_score"),
        ("destinationTableIdentifier", "other_db.score"),
        ("destinationTableIdentifier", "scoré"),
        ("exclude", ["project_id"]),
        ("columns", [{"name": "value"}]),
        ("partitionKey", "scope"),
        ("shardingKey", "scope"),
        ("policyName", "policy"),
        ("partitionByExpr", "month"),
        ("engine", "CH_ENGINE_MERGE_TREE"),
    ],
)
def test_scope_remaps_exclusions_or_unknown_transforms_are_rejected(api, key, value):
    api[2]["cdcStatus"]["config"]["tableMappings"][0][key] = value
    with pytest.raises(InventoryError):
        inspect(api)


def test_missing_effective_mapping_fields_are_not_assumed_default(api):
    del api[2]["cdcStatus"]["config"]["tableMappings"][0]["columns"]
    with pytest.raises(InventoryError):
        inspect(api)


def test_duplicate_effective_destination_is_rejected(api):
    mappings = api[2]["cdcStatus"]["config"]["tableMappings"]
    mappings.append(deepcopy(mappings[0]))
    with pytest.raises(InventoryError, match="duplicate effective"):
        inspect(api)
